<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Structural Equation Models</title>
  <meta name="description" content="Structural Equation Models" />
  <meta name="generator" content="bookdown 0.43 and GitBook 2.6.7" />

  <meta property="og:title" content="Structural Equation Models" />
  <meta property="og:type" content="book" />
  
  
  <meta name="github-repo" content="sarasouther/DataAnalysis" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Structural Equation Models" />
  
  
  

<meta name="author" content="Dr. Sara Souther" />


<meta name="date" content="2025-05-31" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  

<link rel="next" href="structural-equation-models.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<link href="libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet" />
<script src="libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<script src="libs/viz-1.8.2/viz.js"></script>
<link href="libs/DiagrammeR-styles-0.2/styles.css" rel="stylesheet" />
<script src="libs/grViz-binding-1.0.11/grViz.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Statistics for Ecology</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#student-learning-objectives"><i class="fa fa-check"></i><b>1.1</b> Student Learning Objectives</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#downloads"><i class="fa fa-check"></i><b>1.2</b> Downloads</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#description"><i class="fa fa-check"></i><b>1.3</b> Description</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#grading"><i class="fa fa-check"></i><b>1.4</b> Grading</a></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#overview"><i class="fa fa-check"></i><b>1.5</b> Overview</a></li>
<li class="chapter" data-level="1.6" data-path="index.html"><a href="index.html#r"><i class="fa fa-check"></i><b>1.6</b> R</a></li>
<li class="chapter" data-level="1.7" data-path="index.html"><a href="index.html#what-can-statistics-tell-us"><i class="fa fa-check"></i><b>1.7</b> What can statistics tell us?</a></li>
<li class="chapter" data-level="1.8" data-path="index.html"><a href="index.html#sampling-populations"><i class="fa fa-check"></i><b>1.8</b> Sampling populations</a></li>
<li class="chapter" data-level="1.9" data-path="index.html"><a href="index.html#data-types"><i class="fa fa-check"></i><b>1.9</b> Data types</a></li>
<li class="chapter" data-level="1.10" data-path="index.html"><a href="index.html#describing-data"><i class="fa fa-check"></i><b>1.10</b> Describing data</a></li>
<li class="chapter" data-level="1.11" data-path="index.html"><a href="index.html#prework"><i class="fa fa-check"></i><b>1.11</b> Prework</a></li>
<li class="chapter" data-level="1.12" data-path="index.html"><a href="index.html#randomness"><i class="fa fa-check"></i><b>1.12</b> Randomness</a></li>
<li class="chapter" data-level="1.13" data-path="index.html"><a href="index.html#the-sample-point-method"><i class="fa fa-check"></i><b>1.13</b> The sample point method</a></li>
<li class="chapter" data-level="1.14" data-path="index.html"><a href="index.html#combinatorials"><i class="fa fa-check"></i><b>1.14</b> Combinatorials</a></li>
<li class="chapter" data-level="1.15" data-path="index.html"><a href="index.html#union-and-intersection-of-events"><i class="fa fa-check"></i><b>1.15</b> Union and intersection of events</a></li>
<li class="chapter" data-level="1.16" data-path="index.html"><a href="index.html#conditional-probability"><i class="fa fa-check"></i><b>1.16</b> Conditional probability</a></li>
<li class="chapter" data-level="1.17" data-path="index.html"><a href="index.html#multiplicative-law-of-probability-of-independent-events"><i class="fa fa-check"></i><b>1.17</b> Multiplicative Law of Probability of Independent Events</a></li>
<li class="chapter" data-level="1.18" data-path="index.html"><a href="index.html#additive-law-of-probability-of-mutually-exclusive-events"><i class="fa fa-check"></i><b>1.18</b> Additive Law of Probability of Mutually Exclusive Events</a></li>
<li class="chapter" data-level="1.19" data-path="index.html"><a href="index.html#general-additive-law-of-probability"><i class="fa fa-check"></i><b>1.19</b> General Additive Law of Probability</a></li>
<li class="chapter" data-level="1.20" data-path="index.html"><a href="index.html#key-concepts"><i class="fa fa-check"></i><b>1.20</b> Key concepts</a></li>
<li class="chapter" data-level="1.21" data-path="index.html"><a href="index.html#practice-problems"><i class="fa fa-check"></i><b>1.21</b> Practice problems</a></li>
<li class="chapter" data-level="1.22" data-path="index.html"><a href="index.html#basic-hypothesis-testing-review"><i class="fa fa-check"></i><b>1.22</b> Basic hypothesis testing review</a></li>
<li class="chapter" data-level="1.23" data-path="index.html"><a href="index.html#tailed-tests"><i class="fa fa-check"></i><b>1.23</b> Tailed tests</a></li>
<li class="chapter" data-level="1.24" data-path="index.html"><a href="index.html#drawing-conclusions-from-statistics"><i class="fa fa-check"></i><b>1.24</b> Drawing conclusions from statistics</a></li>
<li class="chapter" data-level="1.25" data-path="index.html"><a href="index.html#reporting-results"><i class="fa fa-check"></i><b>1.25</b> Reporting results</a></li>
<li class="chapter" data-level="1.26" data-path="index.html"><a href="index.html#review-problems"><i class="fa fa-check"></i><b>1.26</b> Review problems</a></li>
<li class="chapter" data-level="1.27" data-path="index.html"><a href="index.html#a-foray-into-statistics"><i class="fa fa-check"></i><b>1.27</b> A foray into statistics</a></li>
<li class="chapter" data-level="1.28" data-path="index.html"><a href="index.html#selecting-statistical-analyses"><i class="fa fa-check"></i><b>1.28</b> Selecting statistical analyses</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="structural-equation-models.html"><a href="structural-equation-models.html"><i class="fa fa-check"></i><b>2</b> Structural equation models</a>
<ul>
<li class="chapter" data-level="2.1" data-path="structural-equation-models.html"><a href="structural-equation-models.html#what-are-structural-equation-models"><i class="fa fa-check"></i><b>2.1</b> What are structural equation models?</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="structural-equation-models.html"><a href="structural-equation-models.html#when-should-you-use-sem"><i class="fa fa-check"></i><b>2.1.1</b> When Should You Use SEM?</a></li>
<li class="chapter" data-level="2.1.2" data-path="structural-equation-models.html"><a href="structural-equation-models.html#how-is-sem-different-from-multiple-regression"><i class="fa fa-check"></i><b>2.1.2</b> How is SEM Different from Multiple Regression?</a></li>
<li class="chapter" data-level="2.1.3" data-path="structural-equation-models.html"><a href="structural-equation-models.html#summary"><i class="fa fa-check"></i><b>2.1.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="structural-equation-models.html"><a href="structural-equation-models.html#anatomy-of-a-structural-equation-model"><i class="fa fa-check"></i><b>2.2</b> Anatomy of a Structural Equation Model</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="structural-equation-models.html"><a href="structural-equation-models.html#types-of-variables"><i class="fa fa-check"></i><b>2.2.1</b> Types of Variables</a></li>
<li class="chapter" data-level="2.2.2" data-path="structural-equation-models.html"><a href="structural-equation-models.html#path-diagrams"><i class="fa fa-check"></i><b>2.2.2</b> Path Diagrams</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="structural-equation-models.html"><a href="structural-equation-models.html#building-multivariate-models"><i class="fa fa-check"></i><b>2.3</b> Building Multivariate Models</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="structural-equation-models.html"><a href="structural-equation-models.html#what-is-causality"><i class="fa fa-check"></i><b>2.3.1</b> What is Causality?</a></li>
<li class="chapter" data-level="2.3.2" data-path="structural-equation-models.html"><a href="structural-equation-models.html#why-move-beyond-multiple-regression"><i class="fa fa-check"></i><b>2.3.2</b> Why move beyond Multiple Regression?</a></li>
<li class="chapter" data-level="2.3.3" data-path="structural-equation-models.html"><a href="structural-equation-models.html#meta-modeling-your-system"><i class="fa fa-check"></i><b>2.3.3</b> Meta-Modeling Your System</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="structural-equation-models.html"><a href="structural-equation-models.html#from-concept-to-model"><i class="fa fa-check"></i><b>2.4</b> From Concept to Model</a></li>
<li class="chapter" data-level="2.5" data-path="structural-equation-models.html"><a href="structural-equation-models.html#common-structures-in-causal-diagrams"><i class="fa fa-check"></i><b>2.5</b> Common Structures in Causal Diagrams</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="structural-equation-models.html"><a href="structural-equation-models.html#chains-mediation-paths"><i class="fa fa-check"></i><b>2.5.1</b> Chains (Mediation Paths)</a></li>
<li class="chapter" data-level="2.5.2" data-path="structural-equation-models.html"><a href="structural-equation-models.html#colliders"><i class="fa fa-check"></i><b>2.5.2</b> Colliders</a></li>
<li class="chapter" data-level="2.5.3" data-path="structural-equation-models.html"><a href="structural-equation-models.html#forks-confounding-paths"><i class="fa fa-check"></i><b>2.5.3</b> Forks (Confounding Paths)</a></li>
<li class="chapter" data-level="2.5.4" data-path="structural-equation-models.html"><a href="structural-equation-models.html#descendants-of-colliders"><i class="fa fa-check"></i><b>2.5.4</b> Descendants of Colliders</a></li>
<li class="chapter" data-level="2.5.5" data-path="structural-equation-models.html"><a href="structural-equation-models.html#summary-of-strcutures"><i class="fa fa-check"></i><b>2.5.5</b> Summary of strcutures</a></li>
<li class="chapter" data-level="2.5.6" data-path="structural-equation-models.html"><a href="structural-equation-models.html#identifying-causality"><i class="fa fa-check"></i><b>2.5.6</b> Identifying Causality</a></li>
<li class="chapter" data-level="2.5.7" data-path="structural-equation-models.html"><a href="structural-equation-models.html#backdoor-criterion"><i class="fa fa-check"></i><b>2.5.7</b> Backdoor Criterion</a></li>
<li class="chapter" data-level="2.5.8" data-path="structural-equation-models.html"><a href="structural-equation-models.html#frontdoor-criterion"><i class="fa fa-check"></i><b>2.5.8</b> Frontdoor Criterion</a></li>
<li class="chapter" data-level="2.5.9" data-path="structural-equation-models.html"><a href="structural-equation-models.html#build-your-own-dag-sem-case-study-on-pollinator-impacts-of-vegetation-management"><i class="fa fa-check"></i><b>2.5.9</b> Build your own DAG: SEM Case Study on Pollinator Impacts of Vegetation Management</a></li>
<li class="chapter" data-level="2.5.10" data-path="structural-equation-models.html"><a href="structural-equation-models.html#adjustment-sets"><i class="fa fa-check"></i><b>2.5.10</b> Adjustment Sets</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="structural-equation-models.html"><a href="structural-equation-models.html#chapter-5-covariance-based-estimation-in-sem"><i class="fa fa-check"></i><b>2.6</b> Chapter 5: Covariance-Based Estimation in SEM</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="structural-equation-models.html"><a href="structural-equation-models.html#what-is-covariance-based-sem"><i class="fa fa-check"></i><b>2.6.1</b> What is Covariance-Based SEM?</a></li>
<li class="chapter" data-level="2.6.2" data-path="structural-equation-models.html"><a href="structural-equation-models.html#maximum-likelihood-estimation"><i class="fa fa-check"></i><b>2.6.2</b> Maximum Likelihood Estimation</a></li>
<li class="chapter" data-level="2.6.3" data-path="structural-equation-models.html"><a href="structural-equation-models.html#assumptions-behind-ml-estimation"><i class="fa fa-check"></i><b>2.6.3</b> Assumptions Behind ML Estimation</a></li>
<li class="chapter" data-level="2.6.4" data-path="structural-equation-models.html"><a href="structural-equation-models.html#identifiability"><i class="fa fa-check"></i><b>2.6.4</b> Identifiability</a></li>
<li class="chapter" data-level="2.6.5" data-path="structural-equation-models.html"><a href="structural-equation-models.html#degrees-of-freedom"><i class="fa fa-check"></i><b>2.6.5</b> Degrees of Freedom</a></li>
<li class="chapter" data-level="2.6.6" data-path="structural-equation-models.html"><a href="structural-equation-models.html#sample-size-considerations"><i class="fa fa-check"></i><b>2.6.6</b> Sample Size Considerations</a></li>
<li class="chapter" data-level="2.6.7" data-path="structural-equation-models.html"><a href="structural-equation-models.html#summary-1"><i class="fa fa-check"></i><b>2.6.7</b> Summary</a></li>
<li class="chapter" data-level="2.6.8" data-path="structural-equation-models.html"><a href="structural-equation-models.html#chapter-6-structural-equation-modeling-in-r-with-lavaan"><i class="fa fa-check"></i><b>2.6.8</b> Chapter 6: Structural Equation Modeling in R with lavaan</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="structural-equation-models.html"><a href="structural-equation-models.html#getting-started-with-lavaan-model-specification-estimation-and-interpretation"><i class="fa fa-check"></i><b>2.7</b> Getting Started with lavaan – Model Specification, Estimation, and Interpretation</a>
<ul>
<li class="chapter" data-level="2.7.1" data-path="structural-equation-models.html"><a href="structural-equation-models.html#chapter-7assessing-fit-and-normality"><i class="fa fa-check"></i><b>2.7.1</b> Chapter 7:Assessing Fit and Normality</a></li>
<li class="chapter" data-level="2.7.2" data-path="structural-equation-models.html"><a href="structural-equation-models.html#chapter-8-comparing-models-and-testing-mediation"><i class="fa fa-check"></i><b>2.7.2</b> Chapter 8: Comparing Models and Testing Mediation</a></li>
<li class="chapter" data-level="2.7.3" data-path="structural-equation-models.html"><a href="structural-equation-models.html#chapter-8-latent-variables-as-drivers"><i class="fa fa-check"></i><b>2.7.3</b> Chapter 8: Latent Variables as Drivers</a></li>
<li class="chapter" data-level="2.7.4" data-path="structural-equation-models.html"><a href="structural-equation-models.html#chapter-10-latent-responses-and-measurement-error"><i class="fa fa-check"></i><b>2.7.4</b> Chapter 10: Latent Responses and Measurement Error</a></li>
<li class="chapter" data-level="2.7.5" data-path="structural-equation-models.html"><a href="structural-equation-models.html#chapter-11-local-estimation-and-d-separation"><i class="fa fa-check"></i><b>2.7.5</b> Chapter 11: Local Estimation and D-Separation</a></li>
<li class="chapter" data-level="2.7.6" data-path="structural-equation-models.html"><a href="structural-equation-models.html#chapter-12-introduction-to-piecewise-sem-in-r"><i class="fa fa-check"></i><b>2.7.6</b> Chapter 12: Introduction to Piecewise SEM in R</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="structural-equation-models.html"><a href="structural-equation-models.html#part-1-what-is-piecewise-sem"><i class="fa fa-check"></i><b>2.8</b> Part 1: What is Piecewise SEM?</a>
<ul>
<li class="chapter" data-level="2.8.1" data-path="structural-equation-models.html"><a href="structural-equation-models.html#chapter-13-nonlinearity-and-interaction-in-sem"><i class="fa fa-check"></i><b>2.8.1</b> Chapter 13: Nonlinearity and Interaction in SEM</a></li>
<li class="chapter" data-level="2.8.2" data-path="structural-equation-models.html"><a href="structural-equation-models.html#chapter-14-glms-with-sem-using-piecewisesem"><i class="fa fa-check"></i><b>2.8.2</b> Chapter 14: GLMs with SEM using PiecewiseSEM</a></li>
</ul></li>
<li class="chapter" data-level="2.9" data-path="structural-equation-models.html"><a href="structural-equation-models.html#overview-1"><i class="fa fa-check"></i><b>2.9</b> Overview</a>
<ul>
<li class="chapter" data-level="2.9.1" data-path="structural-equation-models.html"><a href="structural-equation-models.html#chapter-15-categorical-predictors-multigroup-sem"><i class="fa fa-check"></i><b>2.9.1</b> Chapter 15: Categorical Predictors &amp; Multigroup SEM</a></li>
<li class="chapter" data-level="2.9.2" data-path="structural-equation-models.html"><a href="structural-equation-models.html#chapter-16-multigroup-sem-in-r"><i class="fa fa-check"></i><b>2.9.2</b> Chapter 16: Multigroup SEM in R</a></li>
<li class="chapter" data-level="2.9.3" data-path="structural-equation-models.html"><a href="structural-equation-models.html#chapter-17"><i class="fa fa-check"></i><b>2.9.3</b> Chapter 17:</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/sarasouther/DataAnalysis" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Structural Equation Models</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="header">
<h1 class="title">Structural Equation Models</h1>
<p class="author"><em>Dr. Sara Souther</em></p>
<p class="date"><em>2025-05-31</em></p>
</div>
<div id="intro" class="section level1 hasAnchor" number="1">
<h1><span class="header-section-number">Chapter 1</span> Introduction<a href="index.html#intro" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="student-learning-objectives" class="section level2 hasAnchor" number="1.1">
<h2><span class="header-section-number">1.1</span> Student Learning Objectives<a href="index.html#student-learning-objectives" class="anchor-section" aria-label="Anchor link to header"></a></h2>
</div>
<div id="downloads" class="section level2 hasAnchor" number="1.2">
<h2><span class="header-section-number">1.2</span> Downloads<a href="index.html#downloads" class="anchor-section" aria-label="Anchor link to header"></a></h2>
</div>
<div id="description" class="section level2 hasAnchor" number="1.3">
<h2><span class="header-section-number">1.3</span> Description<a href="index.html#description" class="anchor-section" aria-label="Anchor link to header"></a></h2>
</div>
<div id="grading" class="section level2 hasAnchor" number="1.4">
<h2><span class="header-section-number">1.4</span> Grading<a href="index.html#grading" class="anchor-section" aria-label="Anchor link to header"></a></h2>
</div>
<div id="overview" class="section level2 hasAnchor" number="1.5">
<h2><span class="header-section-number">1.5</span> Overview<a href="index.html#overview" class="anchor-section" aria-label="Anchor link to header"></a></h2>

</div>
<div id="r" class="section level2 hasAnchor" number="1.6">
<h2><span class="header-section-number">1.6</span> R<a href="index.html#r" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Add an intro or just use the index file?</p>

</div>
<div id="what-can-statistics-tell-us" class="section level2 hasAnchor" number="1.7">
<h2><span class="header-section-number">1.7</span> What can statistics tell us?<a href="index.html#what-can-statistics-tell-us" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Welcome to our statistical exploration of the natural world! I want you to have an intuitive understanding of what we do when we conduct statistical analysis, understand how to select the appropriate statistical analysis and the assumptions of that analysis, and make a connection between running an analysis in a statistical software package and the statisticese of those unique individuals that we call statisticians. I think this will give you the confidence to tackle any analytical situation!</p>
<p>First off, we are <strong>not</strong> statisticians - whew! We are ecologists and social scientists. This means that we do not need to understand theoretical mathematical frameworks. We need to APPLY statistics appropriately. There will be limits to our mathematical understanding of statistics, and this is OKAY! Think of all of the knowledge about the natural world and conducting field work that we possess that statisticians don’t! I’m happy to dive down math rabbit holes with you, BUT we don’t need to and CAN’T know everything.</p>
<p>Almost all statistical analysis boils down to answering 1 of 2 questions:
<em>Do these groups differ?
</em>Is there a relationship between these variables?</p>
<p>These seem like relatively simple questions to answer, perhaps just by looking at our data, so <strong>Why do we need statistics?</strong></p>
<p>The short answer is: <strong>error</strong> and <strong>sampling</strong>! Whenever we collect data, we introduce <strong>error</strong>; our instruments are imprecise and do not capture an exact measure of whatever you are measuring (e.g., height, weight), and humans make mistakes during measurement collection. Secondly, we are <strong>always</strong> measuring a sub-sample of the true population (<em>true population</em> meaning all representatives of whatever you are trying to measure; this can be grass, marbles, or the tibia of humans). Not only is in intractable in most cases to measure all individuals of whatever you are interested in, even when it is possible to attempt to measure <strong>all</strong> individuals (like in the case of rare plant work), statistics acknowledges that it is <strong>still</strong> unlikely that we are able to completely measure all individuals in your focal population, since individuals may be dormant or challenging to locate. If we could measure all individuals of our population of interest with perfect accurately, we could calculate population <strong>parameters</strong>, or quantities describing populations like averages and variation, rather than estimating these metrics, and in many cases just compare them. In this way, statistics is inherently practical, and asks, what can we say about whatever we are looking at, given our numerous flaws!</p>
</div>
<div id="sampling-populations" class="section level2 hasAnchor" number="1.8">
<h2><span class="header-section-number">1.8</span> Sampling populations<a href="index.html#sampling-populations" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>After a few classes, we will explore sampling methodology in greater depth in order to design appropriate experiments that test a statistical <strong>hypothesis</strong>. Let’s quickly talk about sampling now so that we have a shared understanding and vocabulary to build on - after all, statistics really centers around estimating characteristics of a true population from a sample. The <strong>really, truly</strong> amazing thing is that by properly applying statistics, we can learn practically anything about almost any population using samples!</p>
<p>In statistics, a <strong>population</strong> refers to the all units of the thing that you are interested (i.e., all suriname frogs, all grains of sand, all aspen leaves from a genotype found in southern Arizona). <strong>Note</strong>: Population in statistics differs from the term population in population ecology, where a population refers to a group of individuals in a particular area that interbreed.</p>
<p>A <strong>sample</strong> is a subset of the population that we measure to infer something about the population. Statistical analyses depend on a random sample or must account for non-randomness within the sample. Just imagine, for instance, that you were interested in whether coat color in cats differed between house cats and feral cats. To select the house cat sample, you randomly select house numbers, visit the house and record coat color, thus collecting a random sample. However, to survey feral cats, you go to several cat colonies at night and record the first cat that you see, which are always white or tan. The sample of feral cats introduces bias, and causes you to overestimate the number of light colored feral cats, and underestimate dark feral cats.</p>
<p>We can conduct statistical analysis until the cats come home (ha!), but if your sample is biased, our results will always be meaningless. In the cat example, it was pretty obvious that the researcher was introducing bias, BUT it is REALLY easy to introduce bias in ecological and social research on accident! Imagine that you looking at fire effects on vegetative communities in the Sonoran. In high severity burn areas, there are thickets of cat’s claw (a pokey plant). Without proper field sampling protocols, it is very tempting to avoid establishing plots in the cat claw thickets, thus not capturing true differences in vegetation along burn severity gradients. We can go over field sampling methodology later, but let’s talk about several types of appropriate sampling strategies. The key is that we want our sample to be <strong>representative</strong> of the true population, so that estimates of values (i.e., means, variance) from the sample represent true population parameters.</p>
<p><strong>Simple Random Sampling</strong> is when every sample has an equal likelihood of being selected.</p>
<p>We can quickly and easily generate such a sample in R, using the sample function.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="index.html#cb1-1" tabindex="-1"></a><span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">100</span>, <span class="dv">10</span>, <span class="at">replace=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>##  [1]  77  44  54  85  25  29  20  93  13 100</code></pre>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="index.html#cb3-1" tabindex="-1"></a><span class="co">#1:10000 = numbers to chose among </span></span>
<span id="cb3-2"><a href="index.html#cb3-2" tabindex="-1"></a><span class="co">#number of random numbers you wish to generate</span></span>
<span id="cb3-3"><a href="index.html#cb3-3" tabindex="-1"></a><span class="co">#to replace or not (in other words do you wish for the same number to be selected multiple times)</span></span></code></pre></div>
<p><strong>Random Cluster Sampling</strong> randomly select groups (aka clusters) within a population. This sampling design is used commonly in ecology, when we select random locations for plots, then measure all individuals within those plots. If for instance, we are interested in Ponderosa Pine growth rates on the Coconino National Forest, we would randomly assign points across Pondo habitat on the Coconino. At each point, we would set up a plot in which we measure Ponderosa Pines within an 11.71m radius plot. <strong>Why wouldn’t we just go out to a point and measure 1 tree to create a totally random sample?</strong> The plots are randomly assigned (yay!), but the trees within the plots are not <strong>independent</strong>. In other words, we might expect measures of trees within plot A to be more similar to each other than they are to trees within plot B, due to differences in microsite characteristics, genetic similarity among co-occurring trees, or site history (logging, fire). Luckily, we can account for this non-independence, as long as the plots are random!</p>
<p><strong>Stratified Sampling</strong> draws samples using proportionality based on homogeneous groupings known as strata. This type of sampling is frequently used in ecology to account for landscape differences in key factors. For instance, say you asked to classify vegetation types for a Nature preserve in southern Arizona. The reserve has a large riparian area (25% of the property) with completely different vegetation from the upland area (75%). Random sampling might, by chance, under or over represent one of these two areas. To create a stratified sampling design, you would ensure proportional representation of both areas by randomly placing 25% of the sample points within the riparian area, and 75% of the sample points within the upland area.</p>
<p><strong>Sample size</strong> More is better. However, practically we are often limited by time and money!</p>
<p><strong>Statistical analysis is only one part of presenting your research results.</strong> Generally, a results section in a manuscript includes: statistical results, data description (e.g., describing means, ranges, maxima, minima of groups of interest), and data visualization (i.e., creating beautiful figures). For each analysis that we cover, we will talk about how to present statistical results, describe data, and create appropriate supporting figures.</p>
</div>
<div id="data-types" class="section level2 hasAnchor" number="1.9">
<h2><span class="header-section-number">1.9</span> Data types<a href="index.html#data-types" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Before we start learning to present research results (analysis, description, visualization), let’s talk about data! Data comes in several varieties, and the variety dictates which statistical analysis we choose!</p>
<p><em>Categorical variables</em> are non-numeric variables.
<strong>Examples</strong>: Pet type (dog, cat, fish, bird), Size (small, medium, large), Car type (sedan, SUV), Present/Absent</p>
<p><em>Numerical variables</em> are variables that are numbers, and occur in two forms:
*Discrete = Counts of things (no decimal points/fractions)
Data are discrete when it does not make sense to have a partial number of the variable. For instance, if counting the number of insects in a pond, it does not make sense to count a half a species.
<strong>Examples</strong>: Number of people in a building, number of trees in a plot, number of bugs in a pond</p>
<p>*Continuous = Numerical data that can occur at any value.
These are variables that can occur in any quantity. If you can have a fraction of this variable, it is continuous.
<strong>Examples</strong> = Height, Weight, Length</p>
<p><em>Ordinal variables</em> (sometimes referred to as ranked) can be categorical or numerical, but the order matters.
<strong>Examples</strong> = Grades (A, B, C, D, E), Likert scale variables (Strongly disagree, Agree, Strongly Agree), Class rank (1, 2, 3, 4, 5)</p>
</div>
<div id="describing-data" class="section level2 hasAnchor" number="1.10">
<h2><span class="header-section-number">1.10</span> Describing data<a href="index.html#describing-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>First, let’s take a spin with data description. We are starting here to introduce a few concepts that will be important to understand, as we launch into statistical analysis. We will start by describing continuous data.</p>
<p>Let’s use a simplified version of a dataset that I’m working with right now to look at the performance of several species of pollinator-friendly native species in agricultural gardens. Eventually, we’d like to develop seed to provide to restorationists for restoration of arid and semiarid grasslands. To do this, we need to understand how reliable these species are at establishing, producing seed, and attracting pollinators. Initially, we are conducting experiments with multiple populations of each species to determine how consistently plants grow, reproduce, and perform. Here, We will take a look at the initial heights of 1 population of one species, <em>Asclepias subverticulata</em>.</p>
<p>When doing an actual research write-up, I ask myself ‘What is the most important information for my audience to know about this dataset?’ to guide what descriptions of the data to include. Here, we are just going to play around with numbers and R code!</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="index.html#cb4-1" tabindex="-1"></a><span class="co">#create vector of heights (cm) of one population of A. subverticulata</span></span>
<span id="cb4-2"><a href="index.html#cb4-2" tabindex="-1"></a>sedonapopulation <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">7</span>, <span class="dv">8</span>, <span class="dv">9</span>)</span>
<span id="cb4-3"><a href="index.html#cb4-3" tabindex="-1"></a><span class="co">#take the mean</span></span>
<span id="cb4-4"><a href="index.html#cb4-4" tabindex="-1"></a><span class="fu">mean</span>(sedonapopulation)</span></code></pre></div>
<pre><code>## [1] 5.142857</code></pre>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="index.html#cb6-1" tabindex="-1"></a><span class="co">#calculate variance</span></span>
<span id="cb6-2"><a href="index.html#cb6-2" tabindex="-1"></a><span class="fu">var</span>(sedonapopulation)</span></code></pre></div>
<pre><code>## [1] 7.47619</code></pre>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="index.html#cb8-1" tabindex="-1"></a><span class="co">#calculate standard deviation</span></span>
<span id="cb8-2"><a href="index.html#cb8-2" tabindex="-1"></a><span class="fu">sd</span>(sedonapopulation)</span></code></pre></div>
<pre><code>## [1] 2.734262</code></pre>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="index.html#cb10-1" tabindex="-1"></a><span class="co">#calculate standard error</span></span>
<span id="cb10-2"><a href="index.html#cb10-2" tabindex="-1"></a><span class="co">#base r doesn&#39;t have this function</span></span>
<span id="cb10-3"><a href="index.html#cb10-3" tabindex="-1"></a><span class="co">#so we have to write our own</span></span>
<span id="cb10-4"><a href="index.html#cb10-4" tabindex="-1"></a>std_error <span class="ot">&lt;-</span> <span class="cf">function</span>(x) <span class="fu">sd</span>(x)<span class="sc">/</span><span class="fu">sqrt</span>(<span class="fu">length</span>(x))</span>
<span id="cb10-5"><a href="index.html#cb10-5" tabindex="-1"></a><span class="fu">std_error</span>(sedonapopulation)</span></code></pre></div>
<pre><code>## [1] 1.033454</code></pre>
<p>Most of the time when writing up results, you present a mean (sum of numbers divided by the number of observations), and an estimate of variation (a measure of how different the observations are). Here, we calculated three estimates variation, variance, standard deviation, and standard error.</p>
<p>Since you will occasionally need to include equations in your write-ups, let’s get use to mathematical syntax, with these simple examples.</p>
<p>The formula for the sample mean is: <span class="math inline">\(\mu = \frac{\Sigma x_i}{n}\)</span>;
where <span class="math inline">\(\mu\)</span> indicates the sample mean (sample = group of numbers we are looking at);
<span class="math inline">\(\Sigma\)</span> means to add what ever follows;
<span class="math inline">\(x_{i}\)</span> is the value of one observation; (subscript i is often used to indicate that the action should be repeated for all values);
<span class="math inline">\(n\)</span> is the number of observations</p>
<p><em>Why didn’t we just use <span class="math inline">\(\bar{x}\)</span> to indicate the mean?</em>
Because statisticians typically use <span class="math inline">\(\bar{x}\)</span> to indicate the true mean of the population, and <span class="math inline">\(\mu\)</span> to indicate the sample mean!</p>
<p>Just to show you, what the mean() function is doing, let’s run:</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="index.html#cb12-1" tabindex="-1"></a>sum <span class="ot">=</span> <span class="dv">3</span><span class="sc">+</span><span class="dv">3</span><span class="sc">+</span><span class="dv">3</span><span class="sc">+</span><span class="dv">3</span><span class="sc">+</span><span class="dv">7</span><span class="sc">+</span><span class="dv">8</span><span class="sc">+</span><span class="dv">9</span> <span class="co">#add all the numbers in the sample</span></span>
<span id="cb12-2"><a href="index.html#cb12-2" tabindex="-1"></a>n <span class="ot">=</span> <span class="fu">length</span>(sedonapopulation) <span class="co">#or you can just calculate the number of height measurements</span></span>
<span id="cb12-3"><a href="index.html#cb12-3" tabindex="-1"></a>mean <span class="ot">=</span> sum<span class="sc">/</span>n; mean <span class="co">#divide sum by number</span></span></code></pre></div>
<pre><code>## [1] 5.142857</code></pre>
<p>This formula is simple, but sometimes with more complex formulas, I will solve the equations by hand, to make sure that I understand what is happening!</p>
<p>The formula for variance is: <span class="math inline">\(S^{2} = \frac{\Sigma(x_i - \mu)^{2}}{n - 1}\)</span>
where <span class="math inline">\(S^{2}\)</span> is the sample variance;
<span class="math inline">\(\mu\)</span> is the sample mean (remember from above);
<span class="math inline">\(x_{i}\)</span> is the value of one observation;
<span class="math inline">\(n\)</span> is the number of observations</p>
<p>In other words:</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="index.html#cb14-1" tabindex="-1"></a><span class="co">#We determine how much each observation varies from the mean.</span></span>
<span id="cb14-2"><a href="index.html#cb14-2" tabindex="-1"></a>diffobs1 <span class="ot">=</span> mean <span class="sc">-</span> <span class="dv">3</span></span>
<span id="cb14-3"><a href="index.html#cb14-3" tabindex="-1"></a>diffobs2 <span class="ot">=</span> mean <span class="sc">-</span> <span class="dv">3</span></span>
<span id="cb14-4"><a href="index.html#cb14-4" tabindex="-1"></a>diffobs3 <span class="ot">=</span> mean <span class="sc">-</span> <span class="dv">3</span></span>
<span id="cb14-5"><a href="index.html#cb14-5" tabindex="-1"></a>diffobs4 <span class="ot">=</span> mean <span class="sc">-</span> <span class="dv">3</span></span>
<span id="cb14-6"><a href="index.html#cb14-6" tabindex="-1"></a>diffobs5 <span class="ot">=</span> mean <span class="sc">-</span> <span class="dv">7</span> </span>
<span id="cb14-7"><a href="index.html#cb14-7" tabindex="-1"></a>diffobs6 <span class="ot">=</span> mean <span class="sc">-</span> <span class="dv">8</span></span>
<span id="cb14-8"><a href="index.html#cb14-8" tabindex="-1"></a>diffobs7 <span class="ot">=</span> mean <span class="sc">-</span> <span class="dv">9</span> </span>
<span id="cb14-9"><a href="index.html#cb14-9" tabindex="-1"></a></span>
<span id="cb14-10"><a href="index.html#cb14-10" tabindex="-1"></a><span class="co">#Then we square each of these. </span></span>
<span id="cb14-11"><a href="index.html#cb14-11" tabindex="-1"></a>diffobj1_sq <span class="ot">=</span> diffobs1<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb14-12"><a href="index.html#cb14-12" tabindex="-1"></a>diffobj2_sq <span class="ot">=</span> diffobs2<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb14-13"><a href="index.html#cb14-13" tabindex="-1"></a>diffobj3_sq <span class="ot">=</span> diffobs3<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb14-14"><a href="index.html#cb14-14" tabindex="-1"></a>diffobj4_sq <span class="ot">=</span> diffobs4<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb14-15"><a href="index.html#cb14-15" tabindex="-1"></a>diffobj5_sq <span class="ot">=</span> diffobs5<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb14-16"><a href="index.html#cb14-16" tabindex="-1"></a>diffobj6_sq <span class="ot">=</span> diffobs6<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb14-17"><a href="index.html#cb14-17" tabindex="-1"></a>diffobj7_sq <span class="ot">=</span> diffobs7<span class="sc">^</span><span class="dv">2</span></span></code></pre></div>
<p><em>Why do we square the differences rather than just adding them up?</em>
Because differences will be positive and negative. If we added them without squaring, sample differences would negate each other. We want an estimate of the absolute differences of samples from the mean.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="index.html#cb15-1" tabindex="-1"></a><span class="co">#Then we add the differences up.</span></span>
<span id="cb15-2"><a href="index.html#cb15-2" tabindex="-1"></a>sumofsquares <span class="ot">=</span> <span class="fu">sum</span>(diffobj1_sq, diffobj2_sq, diffobj3_sq, diffobj4_sq, diffobj5_sq, diffobj6_sq, diffobj7_sq)</span>
<span id="cb15-3"><a href="index.html#cb15-3" tabindex="-1"></a><span class="co">#Divide the sum of squares by n - 1.</span></span>
<span id="cb15-4"><a href="index.html#cb15-4" tabindex="-1"></a>variance <span class="ot">=</span> sumofsquares<span class="sc">/</span>(n<span class="dv">-1</span>); variance </span></code></pre></div>
<pre><code>## [1] 7.47619</code></pre>
<p><em>Why n - 1 instead of n?</em>
One reason is that, theoretically, because we are taking the mean of a sample, rather than all individuals, we underestimate the variance, so taking n-1 corrects that bias. Consider it a penalty for measuring a sample, not the entire population! Another practical reason is that dividing by n-1 makes the variance of a single sample undefined (unsolvable) rather than zero (solvable)</p>
<p>For standard deviation, we just take the square root of the variance, to remove the effect of squaring the differences when calculating the variance, and thus contextualizing our estimate of variation with regard to the mean. For example, the variance for the Sedona population is 7.48, larger than the sample mean of 5.12; while the standard deviation is 2.73, indicating that you would expect most observations to be 5.12 +/- 2.73 (we’ll get to quantiles in a minute).</p>
<p>The formula for standard deviation is: <span class="math inline">\(\sigma = \sqrt\frac{\Sigma(x_i - \mu)^{2}}{n - 1}\)</span>
where <span class="math inline">\(\sigma\)</span> is the sample variance;
<span class="math inline">\(\mu\)</span> is the sample mean;
<span class="math inline">\(x_{i}\)</span> is the value of one observation;
<span class="math inline">\(n\)</span> is the number of observations.</p>
<p>Finally, standard error and confidence intervals (we’ll get to confidence intervals later) are the most common metrics of variance presented in journals.</p>
<p>The formula for standard error is: <span class="math inline">\(SE = \frac{\sigma}{\sqrt n}\)</span>
where <span class="math inline">\(SE\)</span> is standard error of the sample;
<span class="math inline">\(\sigma\)</span> is the standard deviation; and
<span class="math inline">\(n\)</span> is the number of samples.</p>
<p><em>Why do we divide the standard deviation by the square root of the sample size to get standard error?</em>
While standard deviation measures the variation of the sample, standard error is meant to estimate the variation of the entire population of samples, if we could measure all individuals accurately. By dividing by the <span class="math inline">\(\sqrt n\)</span>, the larger the sample size, the lower the error, because you have a more complete estimate of the true mean. In other words, standard deviation is just a measure of the variation of our sample, while standard error also incorporates information about our sampling process (how many individuals we have sampled). <em>Want to delve deep into standard error and deviation (me neither - ha)?: Google central limit theorem + standard error / standard deviation.</em></p>
<p>Means and variance measures are the most common way to describe quantitative data. However, several other metrics are useful for understanding the nature of your data and making decisions about analyses. A comprehensive understanding of your dataset includes describing these four features:
<em>Location (Mean, Median)
</em>Spread (Variability)
<em>Shape (Normal, skewed)
</em>Outliers</p>
<p>We’ve talked about means. The median is just the central number in the dataset, and helps you identify skewness.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="index.html#cb17-1" tabindex="-1"></a><span class="co">#an example of an unskewed population</span></span>
<span id="cb17-2"><a href="index.html#cb17-2" tabindex="-1"></a>sedona_unskewed <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>, <span class="dv">7</span>)</span>
<span id="cb17-3"><a href="index.html#cb17-3" tabindex="-1"></a><span class="fu">mean</span>(sedona_unskewed)</span></code></pre></div>
<pre><code>## [1] 4</code></pre>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="index.html#cb19-1" tabindex="-1"></a><span class="fu">median</span>(sedona_unskewed)</span></code></pre></div>
<pre><code>## [1] 4</code></pre>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="index.html#cb21-1" tabindex="-1"></a><span class="co">#previous sedona population; skewed</span></span>
<span id="cb21-2"><a href="index.html#cb21-2" tabindex="-1"></a>sedonapopulation <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">7</span>, <span class="dv">8</span>, <span class="dv">9</span>)</span>
<span id="cb21-3"><a href="index.html#cb21-3" tabindex="-1"></a><span class="fu">mean</span>(sedonapopulation)</span></code></pre></div>
<pre><code>## [1] 5.142857</code></pre>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="index.html#cb23-1" tabindex="-1"></a><span class="fu">median</span>(sedonapopulation)</span></code></pre></div>
<pre><code>## [1] 3</code></pre>
<p>In an unskewed population, the mean will equal the median. Skew may not seem important, but it has statistical ramifications, AND it tells us something meaningful about the data. For instance, what if I said that mean price of a home in Flagstaff is 350K, but the median price of a home is 300K? We would know the that average house prices are driven up by a smaller number of expensive homes.</p>
<p>We can quantify skew by comparing means and medians (mean &gt; median = right-skewed; median &gt; mean = left-skewed), but it is helpful to visualize the shape of data with a <strong>histogram</strong>. A <strong>histogram</strong> is a graph of the frequency of different measurements.</p>
<p>Let’s add a few more observations to our Sedona populations (skewed and unskewed) and check out the look of the data!</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="index.html#cb25-1" tabindex="-1"></a>sedona_unskewed <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">7</span>, <span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">6</span>, <span class="dv">6</span>, <span class="dv">5</span>, <span class="dv">5</span>, <span class="dv">5</span>, <span class="dv">5</span>, <span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">4</span>, <span class="fl">0.5</span>)</span>
<span id="cb25-2"><a href="index.html#cb25-2" tabindex="-1"></a><span class="fu">mean</span>(sedona_unskewed)</span></code></pre></div>
<pre><code>## [1] 3.975</code></pre>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="index.html#cb27-1" tabindex="-1"></a><span class="fu">median</span>(sedona_unskewed)</span></code></pre></div>
<pre><code>## [1] 4</code></pre>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="index.html#cb29-1" tabindex="-1"></a><span class="co">#I&#39;m renaming sedonapopulation, sedona_skewed for this example</span></span>
<span id="cb29-2"><a href="index.html#cb29-2" tabindex="-1"></a>sedona_skewed <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">7</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">6</span>, <span class="dv">7</span>, <span class="dv">8</span>, <span class="dv">9</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">2</span>)</span>
<span id="cb29-3"><a href="index.html#cb29-3" tabindex="-1"></a><span class="fu">mean</span>(sedona_skewed)</span></code></pre></div>
<pre><code>## [1] 4.454545</code></pre>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="index.html#cb31-1" tabindex="-1"></a><span class="fu">median</span>(sedona_skewed)</span></code></pre></div>
<pre><code>## [1] 4</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-8-1.png" width="672" />
In this relatively unskewed example, the tails are approximately even. This shape is also referred to as a normal or Gaussian distribution.
<img src="_main_files/figure-html/unnamed-chunk-9-1.png" width="672" />
Here, we superimposed the bellshaped Normal or Gaussian distribution.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-10-1.png" width="672" />
In this example of skewed data, the tail tapers to the right, indicated that the data is skewed to the right.</p>
<p>In order to explain outliers, we need to look at quantiles! Quantiles are proportions of your data, in other words a way to break your data into chunks to understand spread. You can break your data into as many quantiles as you would like, but it is most common to break your data into 4 parts, also called quartiles. (If you break data into 5 parts, the components are called quintiles, 10 parts = deciles, 100 parts = percentiles).</p>
<p>When you break data into quartiles, roughly 25 percent of the data occurs within each data chunk. The first chunk of the dataset contains 25% of the data (25th percentile; 25% of the data fall at or below this cut-off) is called the first quartile, the 50th percentile is called the sample median or the second quartile, the 75th percentile is called the third quartile.</p>
<p>Box and whisker plots are commonly used to quickly examine quartiles. Let’s check out our plant height data again, using a box and whisker plot.
<img src="_main_files/figure-html/unnamed-chunk-11-1.png" width="672" />
In the plot shown here, the box encapsulates the Interquartile Range (IQR); the center of the data ranging from the 25th percentile to the 75th. The black line in the middle of the box is the median (also called the 50th percentile, because it bisects the dataset; half of the data occur above the median and half below). The lines emerging from the box (whiskers) indicate the extent of the first and third quartiles, and usually corresponding with the minimum and maximum values of the dataset, unless there are <strong>outliers</strong>. An outlier is a datapoint that occurs outside of the 1st or 3rd quantile. Let’s add one to our Sedona dataset, and see how it is represented on the box and whisker plot.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="index.html#cb33-1" tabindex="-1"></a><span class="co">#Let&#39;s add a plant height of 20.</span></span>
<span id="cb33-2"><a href="index.html#cb33-2" tabindex="-1"></a>sedona_skewed <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">7</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">6</span>, <span class="dv">7</span>, <span class="dv">8</span>, <span class="dv">9</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">2</span>, <span class="dv">20</span>)</span>
<span id="cb33-3"><a href="index.html#cb33-3" tabindex="-1"></a><span class="fu">boxplot</span>(sedona_skewed, <span class="at">main=</span><span class="st">&quot;Skewed&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;Plant height (cm)&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-12-1.png" width="672" />
The outlier appears as a dot on the box and whisker plot, and is the maximum value of the dataset.</p>
<p>One other thing to note: Standard deviation also breaks data into meaningful segments, but is only used when data conform to a normal distribution; the mean +/- 1 SD accounts for 68% of the data, +/-2 SDs contains 95% of data, and +/- 3SD includes 99% of data. That said, I’ve never presented standard deviation in a manuscript; it is much more common to include standard error or confidence intervals (discussed later).</p>
<p>We’ve played around a lot with data, but what do you actually need to take away from this?
<em>Data types (Categorical, Numerical discrete, Numerical continuous, Ordinal)
<strong>Why?</strong> We will select analyses based on data type.
</em>The two basic questions that most statistical analyses answer.
<strong>Why?</strong> This will help you define what statistics can and can’t do and bound our learning space!
<em>Ways to describe numerical continuous data (Location, Spread, Shape, Outliers).
<strong>Why?</strong> You will describe your results using these concepts in write-up AND these concepts will be important for certain analyses.
</em>Know how to calculate mean, median, and standard error.
<strong>Why?</strong> These are typical ways to describe data in results sections.
<em>Start to familiarize yourself with mathematical annotation.
<strong>Why?</strong> You may need to include equations in your methods section.
</em>Start to familiarize yourself with R code.
<strong>Why?</strong> Most researchers now use R to analyze, describe, and visualize their data.
*Be able to interpret a histogram and box-whisker plot.
<strong>Why?</strong> These are commonly used ways to visualize data.</p>

</div>
<div id="prework" class="section level2 hasAnchor" number="1.11">
<h2><span class="header-section-number">1.11</span> Prework<a href="index.html#prework" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><em>Listen to the podcast on stochasticity
</em>Reads on randomness and determinism:
<a href="https://towardsdatascience.com/when-science-and-philosophy-meet-randomness-determinism-and-chaos-abdb825c3114" class="uri">https://towardsdatascience.com/when-science-and-philosophy-meet-randomness-determinism-and-chaos-abdb825c3114</a>
*Load packages and datasets</p>
</div>
<div id="randomness" class="section level2 hasAnchor" number="1.12">
<h2><span class="header-section-number">1.12</span> Randomness<a href="index.html#randomness" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Randomness is statistically a simple concept with incredible repercussions for understanding natural systems, human decisions, and, well, life! One of the most interesting panels that I attended as a graduate student was a debate between scientific and religious philosophers over the meaning of randomness. There were a range of viewpoints; the theologian believed that randomness was where the divine could work; at the other extreme, the science philosopher believed that there is no such thing as random, only that we haven’t developed the capacity to measure what we perceive as random, and that everything we experience is a deterministic outcome of physics manifest in the world around us.</p>
<p>As I write this lesson, I’m sitting on the couch with my younger child watching Jurassic Park. Ian Malcolm has just introduced himself as a ‘chaotician’ (he he). Chaos theory is one way to explain what appears to us as ‘randomness’, because small initial differences in conditions of complex systems leads to extremely different end states, even when the same deterministic rules apply to that system. The ‘butterfly effect’ (a butterfly flaps its wings in Asia causes a tornado in Texas) is often used to describe this core concept of chaos (the example originally created by Edward Norton Lorenz used a seagull instead of a butterfly). Chaos theory is incorporated into modeling simulations (particularly in population biology).</p>
<p>In statistics, we have specific definition of randomness: The case when each item in a set has an equal probably of being selected. Statistics also acknowledges unexplained variation in nature, but doesn’t distinguish between true randomness or the inability to perfectly measure all variables explaining an observed phenomenon. Instead, all unpredictability is lumped together. The difference between the true value of an estimate (e.g., mean hieght of giraffes, slope describing the relationship between snail shell length and speed) and the observed estimate is called ‘error’. We use statistical models to parse ‘error’ (unexplained variation in the response variable) from treatment effects (variation in the response variable explained by the explanatory variables). [Add info on random effects here or introduce later?]</p>
<p>Statistical error can arise for several reasons: random variation inherent to natural systems, mistakes during measurement or data collection, inaccuracy of measuring devices, omitted variables. As long as this error isn’t ‘systematic’, we accept that it is there, complete statistical analysis and move-on. However, <strong>systematic error</strong>, whenever you are directionally biasing your sample, or biasing your sampling in the same way, is something to be avoided when designing your experiment and collecting data. An example of a systematic measure would be if you are trying to estimate the mean weight of blue morpho butterflies in southern Brazil, and you never zero your balance. The true mean weight is lower than the mean weight that you calculate.</p>
<p>Since randomness is inherent, we need to calculate the probability that we
Our ability to say that an observed effect is statistically significant is based on probability: <strong>the proportion of times an event occurs in repeated trials</strong> or more generally , <strong>the quantitative measure of one’s belief in the occurrence of a future event</strong>. In other words, when conducting a statistical analysis, we need to be able to determine the likelihood that two or more groups differ by chance, or that an observed a relationship occurred by chance. Remember that probabilities vary between 0 and 1, with 0 indicating no chance of an event occurring and 1 indicating a 100% chance of an event occurring.</p>
<p>Because statistics relies so heavily on probability, let’s review some basic concepts. Prepare yourself for lots of focus on ‘true coins’ (coins that have the equal likelihood have being heads or tails) and dice! Rolling dice and flipping coins are random events, and we will use them to look at predictability! [When to introduce Bayesian vs Frequentist concepts?]</p>
</div>
<div id="the-sample-point-method" class="section level2 hasAnchor" number="1.13">
<h2><span class="header-section-number">1.13</span> The sample point method<a href="index.html#the-sample-point-method" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The sample point method is one method of determining the likelihood of an event, and entails the following steps:
<em>Define the sample space, S, by listing all possible outcomes of the ‘experiment’ or ‘trial’ you are conducting.
</em>Assign probabilities to all sample points, Pi, such that the probability of all events within the experiment tally to 1.
*Sum all sample points that constitute the outcome you are interested in to find the probability of that outcome.</p>
<p>Let’s practice this concept with an example. Let’s calculate the probability of getting two heads in three tosses of a fair coin.</p>
<table>
<caption><span id="tab:unnamed-chunk-14">Table 1.1: </span>Sample Space</caption>
<thead>
<tr class="header">
<th align="right">Outcome</th>
<th align="left">Toss1</th>
<th align="left">Toss2</th>
<th align="left">Toss3</th>
<th align="left">Abbreviated</th>
<th align="right">Probability</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="left">Heads</td>
<td align="left">Heads</td>
<td align="left">Heads</td>
<td align="left">HHH</td>
<td align="right">0.125</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="left">Heads</td>
<td align="left">Heads</td>
<td align="left">Tails</td>
<td align="left">HHT</td>
<td align="right">0.125</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="left">Heads</td>
<td align="left">Tails</td>
<td align="left">Heads</td>
<td align="left">HTH</td>
<td align="right">0.125</td>
</tr>
<tr class="even">
<td align="right">4</td>
<td align="left">Tails</td>
<td align="left">Heads</td>
<td align="left">Heads</td>
<td align="left">THH</td>
<td align="right">0.125</td>
</tr>
<tr class="odd">
<td align="right">5</td>
<td align="left">Tails</td>
<td align="left">Tails</td>
<td align="left">Heads</td>
<td align="left">TTH</td>
<td align="right">0.125</td>
</tr>
<tr class="even">
<td align="right">6</td>
<td align="left">Tails</td>
<td align="left">Heads</td>
<td align="left">Tails</td>
<td align="left">THT</td>
<td align="right">0.125</td>
</tr>
<tr class="odd">
<td align="right">7</td>
<td align="left">Heads</td>
<td align="left">Tails</td>
<td align="left">Tails</td>
<td align="left">HTT</td>
<td align="right">0.125</td>
</tr>
<tr class="even">
<td align="right">8</td>
<td align="left">Tails</td>
<td align="left">Tails</td>
<td align="left">Tails</td>
<td align="left">TTT</td>
<td align="right">0.125</td>
</tr>
</tbody>
</table>
<p>The first step is to define the sample space for this experiment, by showing all possible outcomes of tossing a coin 3 times, as we have done in the table, called ‘Sample Space’. Since this is a fair or balanced coin, all of the outcomes are equally likely, so we assign them a probability of 1/8. Then, we can simply sum the runs that meet our criterion of 2 heads (HHT, HTH, THH): 1/8 + 1/8 + 1/8 = 0.375.</p>
<p>The equation of an event occurring (A) is: <span class="math inline">\(P(A) =\frac{n_a}{N}\)</span> where P(A) is the probability of event A equals the number of points constituting event A (<span class="math inline">\(n_a\)</span>) divided by the total number of sample points (N). Applying this equation to the above example, P(A) = <span class="math inline">\(\frac{3}{8} = 0.375\)</span></p>
</div>
<div id="combinatorials" class="section level2 hasAnchor" number="1.14">
<h2><span class="header-section-number">1.14</span> Combinatorials<a href="index.html#combinatorials" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Because defining the sample space can be cumbersome for larger sample spaces, we can use combinatorial math, specifically the <em>mn</em> rule, to calculate sample space! The <em>mn</em> rule simply states that if one group contains <em>m</em> elements and another group contains <em>n</em> elements, you can for <em>m</em> <em>x</em> <em>n</em> pairs containing an element from each group. For instance, if we were determining the sample space for outcomes of rolling 2, 6-sided dice, we could multiply 6 x 6 (or <span class="math inline">\(6^2\)</span>).</p>
<p><img src="/Users/sks379/Desktop/GraduateStudents/Stats%20and%20Lit%20Review%20Lessons/Class2_Probability/dice.png" alt="Sample space for a single roll of 2 die." />
Using the equation for calculating the probability of an event, what is the probability of rolling double 6s?</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="index.html#cb34-1" tabindex="-1"></a>answer <span class="ot">=</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">36</span>; answer</span></code></pre></div>
<pre><code>## [1] 0.02777778</code></pre>
<p>Let’s try another example with even larger sample space: Calculate the probability of each person in a class of 14 students has a different birthday. In this case, a sample point consists of 14 dates, since there are 14 different students. Assuming that each student has the same probability of being born on any one of 365 days (over course in the real world the likelihood of being born on particular dates differs). The total number of sample points is <span class="math inline">\(N = 365^{14}\)</span> (i.e., there are 365 possible birthdays for Student 1, 365 possible birthdays for student 2, yielding 716835279219613000000000000000000000 possible combinations of b-days). To calculate the probability that each student has a different birthday, you would apply the same equation as above, but calculate the number of points to satisfy our event, keeping in mind that there are 365 birthdays possible for Student 1, 264 possible birthdays for Student 2, 263 possible birthdays for Student 3, and so on, as:</p>
<p>P(A) = <span class="math inline">\(\frac{n_a}{N} = \frac{365 \times 364 \times 363 \dots \times 352}{365^{14}}=0.7769\)</span></p>
<p>Sample points can be represented as sequences of numbers or symbols. An ordered arrangement of of distinct objects is called a <em>permutation</em>. We can calculate the sample space as total number of distinct ways of arranging these symbols or numbers in a sequence, using the following equation:</p>
<p><span class="math inline">\(P_r^n = n(n-1)(n-2)\dots(n-r+1) = \frac{n!}{(n-r)!}\)</span> where <span class="math inline">\(n! = n \times (n-1) \times (n-2) \times\dots\times2\times1\)</span>, where the total number of ordering <span class="math inline">\(n\)</span> objects taken <span class="math inline">\(r\)</span> at a time.
Quick factorial review and calculating in r</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="index.html#cb36-1" tabindex="-1"></a><span class="co">#factorial of 5 or 5!</span></span>
<span id="cb36-2"><a href="index.html#cb36-2" tabindex="-1"></a>factorial <span class="ot">&lt;-</span> <span class="dv">5</span><span class="sc">*</span><span class="dv">4</span><span class="sc">*</span><span class="dv">3</span><span class="sc">*</span><span class="dv">2</span><span class="sc">*</span><span class="dv">1</span>; factorial</span></code></pre></div>
<pre><code>## [1] 120</code></pre>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="index.html#cb38-1" tabindex="-1"></a>factorialR <span class="ot">&lt;-</span> <span class="fu">factorial</span>(<span class="dv">5</span>); factorialR</span></code></pre></div>
<pre><code>## [1] 120</code></pre>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="index.html#cb40-1" tabindex="-1"></a><span class="co">#remember that </span></span>
<span id="cb40-2"><a href="index.html#cb40-2" tabindex="-1"></a><span class="fu">factorial</span>(<span class="dv">0</span>)</span></code></pre></div>
<pre><code>## [1] 1</code></pre>
<p>Let’s apply this equation: How many trinucleotide sequences can be formed without repeating a nucleotide? To put this another way, we ar interested in the number of ways of ordering <span class="math inline">\(n = 4\)</span> elements (A, T, C, and G) taken 3 at a time (trinucleotide = 3; <span class="math inline">\(r = 3\)</span>).</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="index.html#cb42-1" tabindex="-1"></a>permutations <span class="ot">=</span> (<span class="fu">factorial</span>(<span class="dv">4</span>))<span class="sc">/</span><span class="fu">factorial</span>(<span class="dv">4-3</span>); permutations</span></code></pre></div>
<pre><code>## [1] 24</code></pre>
<p>When the sequence is not important, we use a different formula. For unordered sets of r elements chosen without replacement from n available elements are called combinations, with total number of combinations calculated as:</p>
<p><span class="math inline">\(C^n_r = \frac{n!}{r!(n-r)!}\)</span></p>
<p>What are the number of combinations of 2 colors of m&amp;ms that we can select out of the 5 total colors?</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="index.html#cb44-1" tabindex="-1"></a>combinations <span class="ot">=</span> (<span class="fu">factorial</span>(<span class="dv">5</span>))<span class="sc">/</span>(<span class="fu">factorial</span>(<span class="dv">2</span>)<span class="sc">*</span><span class="fu">factorial</span>(<span class="dv">5-2</span>)); combinations</span></code></pre></div>
<pre><code>## [1] 10</code></pre>
<p>If it’s helpful, you can test the answer by hand, using these colors: tan, brown, orange, red, and green.</p>
<p>Again, the basic concepts of the sample-point method, are to define sample space, and either assign probabilities to all sample points, then sum the probabilities OR calculate <span class="math inline">\(P(A) =\frac{n_a}{N}\)</span> where P(A) is the probability of event A equals the number of points constituting event A (<span class="math inline">\(n_a\)</span>) divided by the total number of sample points (N). <strong>Note</strong>: these are the same equation, they only differ in terms of when you calculate the probability (of the points individually, or at the end after you define the sample space / and event number). When sample space is large, it is easier to use combinatorial math to calculate the points and the sample space.</p>
<p>Let’s apply this understanding of probability to calculate the likelihood of two events occurring.</p>
</div>
<div id="union-and-intersection-of-events" class="section level2 hasAnchor" number="1.15">
<h2><span class="header-section-number">1.15</span> Union and intersection of events<a href="index.html#union-and-intersection-of-events" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>You might be gleaning that defining the appropriate sample space is critically important to correctly calculate probabilities of particular events occurring. Also important is the understanding relationship between events of interest for which we calculate probabilities. These concepts are also important for understanding Boolean operators, computer coding concepts, and modeling.</p>
<p><strong>Note</strong>: Boolean operators form the basis of mathematical sets and database logic. They connect your search words together to either narrow or broaden your set of results. The three basic boolean operators are: AND, OR, and NOT. (I copied and pasted this from the internet, should rewrite a bit - this is just taking a while)</p>
<p><strong>Union of events</strong>
Union of events: What is the likelihood of both events <em>A</em> and <em>B</em> (this can be written as <span class="math inline">\(A \cup B\)</span>)? contains all sampling points for A <em>or</em> B.</p>
<p><img src="/Users/sks379/Desktop/GraduateStudents/Stats%20and%20Lit%20Review%20Lessons/Class2_Probability/Union.png" alt="Venn diagram indicating a union of events or an ‘or’ statement." />
<strong>Example calculating probability of union event</strong>:
What is the likelihood of rolling an odd number (Event A) on a 6-side fair die OR that is less than 4 (Event B)?
Event A = 1, 3, 5
Event B = 1, 2, 3</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="index.html#cb46-1" tabindex="-1"></a><span class="co">#The sample space is all possible rolls</span></span>
<span id="cb46-2"><a href="index.html#cb46-2" tabindex="-1"></a>samplespace <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>); samplespace</span></code></pre></div>
<pre><code>## [1] 1 2 3 4 5 6</code></pre>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="index.html#cb48-1" tabindex="-1"></a><span class="co">#We will use Boolean operators in R. They will return TRUE / FALSE statements.</span></span>
<span id="cb48-2"><a href="index.html#cb48-2" tabindex="-1"></a><span class="co">#Below we tell R to look for odd numbers OR (indicated by line) </span></span>
<span id="cb48-3"><a href="index.html#cb48-3" tabindex="-1"></a><span class="co">#numbers less than 4.</span></span>
<span id="cb48-4"><a href="index.html#cb48-4" tabindex="-1"></a>unionevent <span class="ot">&lt;-</span> (samplespace<span class="sc">%%</span><span class="dv">2</span><span class="sc">==</span><span class="dv">1</span>) <span class="sc">|</span> (samplespace <span class="sc">&lt;</span> <span class="dv">4</span>); unionevent</span></code></pre></div>
<pre><code>## [1]  TRUE  TRUE  TRUE FALSE  TRUE FALSE</code></pre>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="index.html#cb50-1" tabindex="-1"></a><span class="co">#If the conditions are satisfied, TRUE will be returned.</span></span>
<span id="cb50-2"><a href="index.html#cb50-2" tabindex="-1"></a><span class="co">#If conditions are not met, FALSE will be returned.</span></span>
<span id="cb50-3"><a href="index.html#cb50-3" tabindex="-1"></a></span>
<span id="cb50-4"><a href="index.html#cb50-4" tabindex="-1"></a><span class="co">#Now, let&#39;s calculate the probability using techniques that you </span></span>
<span id="cb50-5"><a href="index.html#cb50-5" tabindex="-1"></a><span class="co">#have already seen above.</span></span>
<span id="cb50-6"><a href="index.html#cb50-6" tabindex="-1"></a>probunion <span class="ot">&lt;-</span> <span class="dv">4</span><span class="sc">/</span><span class="dv">6</span>; probunion</span></code></pre></div>
<pre><code>## [1] 0.6666667</code></pre>
<p><strong>Intersection of events</strong>
Intersection of events: What is the likelihood of both events <em>A</em> and <em>B</em> (this can be written as <span class="math inline">\(A \cap B\)</span>)? contains all sampling points for A <em>and</em> B.</p>
<p><img src="/Users/sks379/Desktop/GraduateStudents/Stats%20and%20Lit%20Review%20Lessons/Class2_Probability/Intersection.png" alt="Venn diagram indicating an intersection of events or an ‘or’ statement." />
<strong>Example calculating probability of an intersection event</strong>:</p>
<p>What is the likelihood of rolling an odd number (Event A) on a 6-side fair die AND that is less than 4 (Event B)?</p>
<p>Event A = 1, 3, 5
Event B = 1, 2, 3</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="index.html#cb52-1" tabindex="-1"></a><span class="co">#The sample space is all possible rolls</span></span>
<span id="cb52-2"><a href="index.html#cb52-2" tabindex="-1"></a>samplespace <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>); samplespace</span></code></pre></div>
<pre><code>## [1] 1 2 3 4 5 6</code></pre>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="index.html#cb54-1" tabindex="-1"></a><span class="co">#We will use Boolean operators in R. They will return TRUE / FALSE statements.</span></span>
<span id="cb54-2"><a href="index.html#cb54-2" tabindex="-1"></a><span class="co">#Below we tell R to look for odd numbers OR (indicated by line) </span></span>
<span id="cb54-3"><a href="index.html#cb54-3" tabindex="-1"></a><span class="co">#numbers less than 4.</span></span>
<span id="cb54-4"><a href="index.html#cb54-4" tabindex="-1"></a>intersectionevent <span class="ot">&lt;-</span> (samplespace<span class="sc">%%</span><span class="dv">2</span><span class="sc">==</span><span class="dv">1</span>) <span class="sc">&amp;</span> (samplespace <span class="sc">&lt;</span> <span class="dv">4</span>); intersectionevent</span></code></pre></div>
<pre><code>## [1]  TRUE FALSE  TRUE FALSE FALSE FALSE</code></pre>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="index.html#cb56-1" tabindex="-1"></a><span class="co">#If the conditions are satisfied, TRUE will be returned.</span></span>
<span id="cb56-2"><a href="index.html#cb56-2" tabindex="-1"></a><span class="co">#If conditions are not met, FALSE will be returned.</span></span>
<span id="cb56-3"><a href="index.html#cb56-3" tabindex="-1"></a></span>
<span id="cb56-4"><a href="index.html#cb56-4" tabindex="-1"></a><span class="co">#Now, let&#39;s calculate the probability using techniques that you </span></span>
<span id="cb56-5"><a href="index.html#cb56-5" tabindex="-1"></a><span class="co">#have already seen above.</span></span>
<span id="cb56-6"><a href="index.html#cb56-6" tabindex="-1"></a>probintersection <span class="ot">&lt;-</span> <span class="dv">2</span><span class="sc">/</span><span class="dv">6</span>; probintersection</span></code></pre></div>
<pre><code>## [1] 0.3333333</code></pre>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="index.html#cb58-1" tabindex="-1"></a><span class="co">#Just for fun</span></span>
<span id="cb58-2"><a href="index.html#cb58-2" tabindex="-1"></a><span class="co">#The other common Boolean operator used in computer code is &#39;not&#39;</span></span>
<span id="cb58-3"><a href="index.html#cb58-3" tabindex="-1"></a><span class="co">#We want to roll any number except 2</span></span>
<span id="cb58-4"><a href="index.html#cb58-4" tabindex="-1"></a>nottwo <span class="ot">&lt;-</span> samplespace <span class="sc">!=</span> <span class="dv">2</span>; nottwo</span></code></pre></div>
<pre><code>## [1]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE</code></pre>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="index.html#cb60-1" tabindex="-1"></a>probNOTtwo <span class="ot">&lt;-</span> <span class="dv">5</span><span class="sc">/</span><span class="dv">6</span>; probNOTtwo</span></code></pre></div>
<pre><code>## [1] 0.8333333</code></pre>
</div>
<div id="conditional-probability" class="section level2 hasAnchor" number="1.16">
<h2><span class="header-section-number">1.16</span> Conditional probability<a href="index.html#conditional-probability" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Conditional probability indicates a situation when the probability of one event depends on the occurrence of another event. Conditional probability (written as P(A|B), and read as the probability of event A given B) is calculated with the following equation: <span class="math inline">\(P(A|B) = \frac{P(A \cap B)}{P(B)}\)</span> where <span class="math inline">\(A \cap B\)</span> indicates the probability of both event A and event B occurring.</p>
<p><strong>Example</strong>: I roll a die and ask you to guess the number. I want to increase your odds of guessing the correct number, so I tell you that the number is odd. You are going to guess the number 3 - What are your odd of guessing the correct number (odds that the answer is 3; event A) given that the result is an odd number (the answer is an odd number; event B)?</p>
<p>To break this down, the probability of both A and B being true (<span class="math inline">\(A \cap B\)</span>) is 1/6. The likelihood of the roll being a 3 is the limiting factor in essence, so an ‘and’ probability is constrained by the least likely event. Then, we divide 1/6 by the probability of the roll being odd, which is 1/2 since there are 3 odd and 3 even numbers.</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="index.html#cb62-1" tabindex="-1"></a>conditional <span class="ot">&lt;-</span> (<span class="dv">1</span><span class="sc">/</span><span class="dv">6</span>)<span class="sc">/</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">2</span>); conditional </span></code></pre></div>
<pre><code>## [1] 0.3333333</code></pre>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="index.html#cb64-1" tabindex="-1"></a><span class="co">#the likelihood of guessing the correct number, if the number is odd is 1/3.</span></span></code></pre></div>
</div>
<div id="multiplicative-law-of-probability-of-independent-events" class="section level2 hasAnchor" number="1.17">
<h2><span class="header-section-number">1.17</span> Multiplicative Law of Probability of Independent Events<a href="index.html#multiplicative-law-of-probability-of-independent-events" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>For independent events, in other words, two events in which the occurrence of one event doesn’t depend on the occurrence of the other event, the probability of BOTH events occurring is the found by multiplying the probability of each event A and B happening:</p>
<p><span class="math inline">\(P(A \cap B)= P(A) \times P(B)\)</span> where <span class="math inline">\(A \cap B\)</span> indicates the probability of both event A and event B occurring.</p>
<p><strong>Example</strong>: What is the probability of getting heads in two consecutive coin tosses?</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="index.html#cb65-1" tabindex="-1"></a>heads <span class="ot">&lt;-</span> (<span class="dv">1</span><span class="sc">/</span><span class="dv">2</span>)<span class="sc">*</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">2</span>); heads</span></code></pre></div>
<pre><code>## [1] 0.25</code></pre>
</div>
<div id="additive-law-of-probability-of-mutually-exclusive-events" class="section level2 hasAnchor" number="1.18">
<h2><span class="header-section-number">1.18</span> Additive Law of Probability of Mutually Exclusive Events<a href="index.html#additive-law-of-probability-of-mutually-exclusive-events" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>For two events that are mutually exclusive (if event A occurs, then event B cannot occur), the probability of one of two mutually exclusive events happening is found by adding their individuals probabilities.</p>
<p><span class="math inline">\(P(A \cup B)= P(A) + P(B)\)</span> where <span class="math inline">\(A \cap B\)</span> indicates the probability of both event A and event B occurring.</p>
<p><strong>Example</strong>: What is the probability of rolling a 5 and a 6 on a fair die? That’s right! It’s zero, because the definition of mutual exclusivity indicates that if one event occurs the other can’t.</p>
<p><strong>Real example</strong>: What is the probability of rolling a 5 or a 6 on a fair die?</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="index.html#cb67-1" tabindex="-1"></a>fivesix <span class="ot">&lt;-</span> (<span class="dv">1</span><span class="sc">/</span><span class="dv">6</span>)<span class="sc">+</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">6</span>); fivesix</span></code></pre></div>
<pre><code>## [1] 0.3333333</code></pre>
</div>
<div id="general-additive-law-of-probability" class="section level2 hasAnchor" number="1.19">
<h2><span class="header-section-number">1.19</span> General Additive Law of Probability<a href="index.html#general-additive-law-of-probability" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>When events are not mutually exclusive, we apply the general additive law of probability, which is written as: <span class="math inline">\(P(A \cup B) = P(A) + P(B) - P(A \cap B)\)</span> where <span class="math inline">\(P(A \cap B)\)</span> is the intersection of event A and event B. Why do we remove the intersection event?</p>
<p><img src="/Users/sks379/Desktop/GraduateStudents/Stats%20and%20Lit%20Review%20Lessons/Class2_Probability/Union.png" alt="Venn diagram indicating a union of events or an ‘or’ statement." /><br />
We essentially don’t want to double count the intersecting area of Event A and Event B.</p>
<p>You’ve already completed one of these problems, we just hadn’t gone over intersection events. Let’s apply the general additive law of probability to the previous problem:</p>
<p>What is the likelihood of rolling an odd number (Event A) on a 6-side fair die OR that is less than 4 (Event B)?
Event A = 1, 3, 5
Event B = 1, 2, 3</p>
<p>Original calculation:</p>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="index.html#cb69-1" tabindex="-1"></a><span class="co">#The sample space is all possible rolls</span></span>
<span id="cb69-2"><a href="index.html#cb69-2" tabindex="-1"></a>samplespace <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>); samplespace</span></code></pre></div>
<pre><code>## [1] 1 2 3 4 5 6</code></pre>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="index.html#cb71-1" tabindex="-1"></a><span class="co">#We will use Boolean operators in R. They will return TRUE / FALSE statements.</span></span>
<span id="cb71-2"><a href="index.html#cb71-2" tabindex="-1"></a><span class="co">#Below we tell R to look for odd numbers OR (indicated by line) </span></span>
<span id="cb71-3"><a href="index.html#cb71-3" tabindex="-1"></a><span class="co">#numbers less than 4.</span></span>
<span id="cb71-4"><a href="index.html#cb71-4" tabindex="-1"></a>unionevent <span class="ot">&lt;-</span> (samplespace<span class="sc">%%</span><span class="dv">2</span><span class="sc">==</span><span class="dv">1</span>) <span class="sc">|</span> (samplespace <span class="sc">&lt;</span> <span class="dv">4</span>); unionevent</span></code></pre></div>
<pre><code>## [1]  TRUE  TRUE  TRUE FALSE  TRUE FALSE</code></pre>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="index.html#cb73-1" tabindex="-1"></a><span class="co">#If the conditions are satisfied, TRUE will be returned.</span></span>
<span id="cb73-2"><a href="index.html#cb73-2" tabindex="-1"></a><span class="co">#If conditions are not met, FALSE will be returned.</span></span>
<span id="cb73-3"><a href="index.html#cb73-3" tabindex="-1"></a></span>
<span id="cb73-4"><a href="index.html#cb73-4" tabindex="-1"></a><span class="co">#Now, let&#39;s calculate the probability using techniques that you </span></span>
<span id="cb73-5"><a href="index.html#cb73-5" tabindex="-1"></a><span class="co">#have already seen above.</span></span>
<span id="cb73-6"><a href="index.html#cb73-6" tabindex="-1"></a>probunion <span class="ot">&lt;-</span> <span class="dv">4</span><span class="sc">/</span><span class="dv">6</span>; probunion</span></code></pre></div>
<pre><code>## [1] 0.6666667</code></pre>
<p>Calculation using the equation: <span class="math inline">\(P(A \cup B) = P(A) + P(B) - P(A \cap B)\)</span></p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="index.html#cb75-1" tabindex="-1"></a>probA <span class="ot">&lt;-</span> <span class="dv">3</span><span class="sc">/</span><span class="dv">6</span></span>
<span id="cb75-2"><a href="index.html#cb75-2" tabindex="-1"></a>probB <span class="ot">&lt;-</span> <span class="dv">3</span><span class="sc">/</span><span class="dv">6</span></span>
<span id="cb75-3"><a href="index.html#cb75-3" tabindex="-1"></a>intersection <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">3</span></span>
<span id="cb75-4"><a href="index.html#cb75-4" tabindex="-1"></a></span>
<span id="cb75-5"><a href="index.html#cb75-5" tabindex="-1"></a>finalprob <span class="ot">&lt;-</span> probA <span class="sc">+</span> probB <span class="sc">-</span> intersection; finalprob</span></code></pre></div>
<pre><code>## [1] 0.6666667</code></pre>
</div>
<div id="key-concepts" class="section level2 hasAnchor" number="1.20">
<h2><span class="header-section-number">1.20</span> Key concepts<a href="index.html#key-concepts" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><em>Randomness is inherent in natural systems. Whether this randomness is truly random or simply appears random due to the complexity of natural systems, we treat it the same in statistics.
</em>We want to avoid any form of systematic bias in experimental design.
<em>Randomness and other factors are lumped together in what we call statistical error; the difference between a true estimate of a parameter and what we estimate in our sample.
</em>Probability is the proportion of times an event occurs in repeated trials, and varies between 0 and 1.
<em>We practiced a bunch of different ways of calculating probability, for the long-term, what you really need to know is that to calculate probabilities, you need to understand your sample space and the likelihood and relationship of events of interest.
</em>Two great rules of probability are: Additive Law of Probability &amp; the Multiplicative Law of Probability
*Union events and Intersection events</p>
</div>
<div id="practice-problems" class="section level2 hasAnchor" number="1.21">
<h2><span class="header-section-number">1.21</span> Practice problems<a href="index.html#practice-problems" class="anchor-section" aria-label="Anchor link to header"></a></h2>

<p>We will highlight the basic components of a statistical test with a very simple statistical ‘tailed’ test. For this example, we will:
<em>State a hypothesis
</em>Calculate a test statistic
<em>Determine the p-value
</em>Interpret results</p>
</div>
<div id="basic-hypothesis-testing-review" class="section level2 hasAnchor" number="1.22">
<h2><span class="header-section-number">1.22</span> Basic hypothesis testing review<a href="index.html#basic-hypothesis-testing-review" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We are all familiar with the basic scientific process: A researcher makes observations about the natural world, then generates a hypothesis to test a particular explanation of an observed phenomenon within the system, rejects or fails to reject the hypothesis, and reports these findings, growing the understanding of the system. In most day-to-day research, researchers perform the scientific process intuitively, rather than explicitly. For instance, I have never included hypotheses in a manuscript. This isn’t to say you can’t include hypotheses, just that most journals don’t require writing your methods this way, and often space constraints and readability considerations lead authors to avoid including specific hypotheses in write-ups. Frequently, I will include hypotheses in a research proposal to help illustrate key aspects of the system and demonstrate that the statistical tests are testable, but not always! In other words, hypothesis testing is the foundation of scientific inquiry, but easily overlooked, since it often isn’t necessary to explicitly state hypotheses to create scientific products.</p>
<p>Statistical hypothesis testing answers very simple questions, while scientists work in very complex knowledge environments. For beginning researchers, it is important to understand what statistics can tell us, and how this builds information to address amazing and very interesting research questions. Hypotheses allow us to articulate exactly what we are testing in statistics and to organize thoughts and analyses. In Week 1, we discussed that most statistical tests are designed to answer one of two questions: 1) Are there differences between these groups? and 2) are there relationships between these variables? Let’s connect these concepts directly to hypothesis testing.</p>
<p>The <strong>null hypothesis</strong> (<span class="math inline">\(H_0\)</span>) is a statement about a population parameter that would be interesting to reject. The null hypothesis typically asserts that there is no effect or relationship or that results will not deviate from established knowledge.</p>
<p>For instance:
<em>The mean height of giraffes in captivity and in the wild do NOT differ.
</em>The incidence of toenail fungus is the SAME in the control group and the group given anti-fungal medicine.
<em>There is NO relationship between sea grass height and the number of sea snails.
</em>The mean human body temperature is 98.6 degrees Fahrenheit.</p>
<p>Null hypotheses are paired with <strong>alternative hypotheses</strong> (<span class="math inline">\(H_A\)</span>) that represent ALL other possibilities other than that stated in the null hypothesis.</p>
<p>For instance:
<em>The mean height of giraffes in captivity and in the wild differs.
</em>The incidence of toenail fungus is different in the control group and the group given anti-fungal medicine.
<em>There is a relationship between sea grass height and the number of sea snails.
</em>The mean human body temperature is not 98.6 degrees Fahrenheit.</p>
<p>Note that the null hypothesis is very <strong>specific</strong>, while the alternative hypothesis is <strong>general</strong>. Statistical tests are designed to either reject or fail to reject the <strong>null</strong> hypothesis.</p>
</div>
<div id="tailed-tests" class="section level2 hasAnchor" number="1.23">
<h2><span class="header-section-number">1.23</span> Tailed tests<a href="index.html#tailed-tests" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Tailed tests are very simple tests for comparing means or proportions, and are great for illustrating the basic components of a frequentist statistical analysis. Let’s walk through an example! Handedness is common in humans. Around 90% of humans preferentially use their right hand. You’ve been watching your cat, Geraldo, play with his toy mouse, and you notice that he preferentially uses his right paw to bat the mouse around. You start to wonder if cats display handedness like humans! You run around visiting cats and observing their paw usage and determine that 14 cats of the 18 you observe appear to be right-pawed, while 4 preferentially use their left paw. Is this enough evidence to suggest that cats display ‘handedness’ or did this pattern just emerge by chance?</p>
<p><em>Generate hypotheses</em></p>
<p><em>What is the null hypothesis in this case?</em> Remember it must be specific so that we can either reject or fail to reject the null!</p>
<p><span class="math inline">\(H_0\)</span>: Left and right-pawed cats are equally frequent in the population (i.e., Cats are not right or left-pawed).</p>
<p>Note that this null hypothesis is very specific. If we would describe this mathematically, we would say that we expect half the cats (9 / 18) to use their right paws and half to use their left paws. If we express this as a proportion, (<span class="math inline">\(p\)</span>), we are testing whether <span class="math inline">\(p\)</span> = 0.5. Very specific.</p>
<p><em>What is the alternative hypothesis?</em>
<span class="math inline">\(H_A\)</span>: Left and right-pawed cats are not equally frequent in the population.</p>
<p>Note that the alternative hypothesis is very broad and encompasses all other possibilities. Because, in theory, we could observe proportions below 0.5 (1/18 cats are right-handed) or above 0.5 (16/19 cats are right-handed), we refer to this as <strong>two-tailed</strong>.</p>
<p><strong>In a two-tailed test, the alternative hypothesis includes parameters on both sides of the value specified by the null hypothesis.</strong></p>
<p>Before we move on, can you think of an example of a 1-tailed test?
Examples:
<em>Did you score better than the class average?
</em>Is the time to ARD slower when you avoid driving through campus?
Note that we are only interested in values in one direction. In the first example, we are interested in whether your score is &gt;80% (class average). In the second, we are interested in whether your drive time is &lt;10 minutes (time to ARD driving through campus from your house).</p>
<p>How could you phrase the first example to be a 2-sided test?
Answer: Was my score different than the class average? In this case, your score could be higher or lower.</p>
<p><em>Calculate a test statistic</em></p>
<p>We generated our hypotheses. Let’s calculate a test statistic. What is a test statistic?</p>
<p><strong>A test statistic is a quantity calculated from that data used in statistical analysis to evaluate the null hypothesis.</strong></p>
<p>For this simple test, our test statistic will be 14, since this is the number of right-handed cats we observed. We want to ask whether observing 14 out of 18 cats using their right paw is truly different from the null (9 out of 18 cats using their right paw), or did this pattern occur by chance in our sample?</p>
<p><em>Determine the p-value</em></p>
<p>Frequentists statistics is based on the concept of statistical distributions. If we run many trials, we can determine the likelihood of certain events occurring. We refer to the patterns of occurrence of trials as frequency distributions. Let’s illustrate using the data above. A cat can either be right-handed or left-handed (in this case there are no ambidextrous cats). To determine the likelihood that our pattern arose by chance, we conduct numerous trials like a coin toss. We would randomly flip a coin 18 times and record the outcome of each trial; heads being right-pawed, and tails being left-pawed.</p>
<p>Let’s do that now:
<em>Each student take a coin.
</em>Flip the coin 18 times and record number of heads.
*Divide by total number of trials (in this case students) to derive relative frequency for each event.</p>
<p>We probably generated something that looks like the figure below. This is referred to a probability distribution and expresses the relative frequency of particular events occurring. Frequentist statistics derives its name from this probability distribution.</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="index.html#cb77-1" tabindex="-1"></a>paws <span class="ot">&lt;-</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">18</span></span>
<span id="cb77-2"><a href="index.html#cb77-2" tabindex="-1"></a><span class="fu">plot</span>(paws, <span class="fu">dbinom</span>(paws, <span class="dv">18</span>, <span class="fl">0.5</span>), <span class="at">type=</span><span class="st">&#39;h&#39;</span>, <span class="at">ylab=</span><span class="st">&quot;Probability&quot;</span>, <span class="at">xlab=</span><span class="st">&quot;Number Right-pawed Cats&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/cars-1.png" width="672" />
Here is a table of those probabilities:</p>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="index.html#cb78-1" tabindex="-1"></a>probability <span class="ot">&lt;-</span> <span class="fu">dbinom</span>(paws, <span class="dv">18</span>, <span class="fl">0.5</span>)</span>
<span id="cb78-2"><a href="index.html#cb78-2" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">18</span></span>
<span id="cb78-3"><a href="index.html#cb78-3" tabindex="-1"></a>pawtable <span class="ot">&lt;-</span> <span class="fu">cbind</span>(N, probability)</span>
<span id="cb78-4"><a href="index.html#cb78-4" tabindex="-1"></a>pawtableF <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(pawtable); pawtableF</span></code></pre></div>
<pre><code>##     N  probability
## 1   0 3.814697e-06
## 2   1 6.866455e-05
## 3   2 5.836487e-04
## 4   3 3.112793e-03
## 5   4 1.167297e-02
## 6   5 3.268433e-02
## 7   6 7.081604e-02
## 8   7 1.213989e-01
## 9   8 1.669235e-01
## 10  9 1.854706e-01
## 11 10 1.669235e-01
## 12 11 1.213989e-01
## 13 12 7.081604e-02
## 14 13 3.268433e-02
## 15 14 1.167297e-02
## 16 15 3.112793e-03
## 17 16 5.836487e-04
## 18 17 6.866455e-05
## 19 18 3.814697e-06</code></pre>
<p>Take a look at the chart. What is the probability of observing right pawedness in 14 out of 18 cats? Is this difference from the null (9 cats are right-handed, no better than random) big enough to reject the null? To determine this we calculate a p-value.</p>
<p><strong>A p-value is the probability of obtaining the data that we observe if the null hypothesis were true.</strong></p>
<p>In this case, we will generate a p-value for a two-tailed test. To do this, we will add the probabilities of observing 14 right pawed cats or more by chance AND for the possibility of observing 4 or fewer right paws, which would indicate left pawedness.
P-value = Pr[14] + Pr[15] + Pr[16] + Pr[17] + Pr[18] + Pr[4] + Pr[3] + Pr[2] + Pr[1] + Pr[0]</p>
<p>Recall that we can add these probabilities up, since, in our example, we say that being right or left pawed are mutually exclusive events.</p>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="index.html#cb80-1" tabindex="-1"></a>pvalue <span class="ot">&lt;-</span> (<span class="fl">0.0117</span> <span class="sc">+</span> <span class="fl">0.0031</span> <span class="sc">+</span> <span class="fl">0.0006</span> <span class="sc">+</span> <span class="fl">0.00007</span> <span class="sc">+</span> <span class="fl">0.000004</span>)<span class="sc">*</span><span class="dv">2</span>; pvalue</span></code></pre></div>
<pre><code>## [1] 0.030948</code></pre>
<p>We generate a P-value of 0.031.</p>
<p>In most sciences, we have agreed on a threshold of 0.05 for establishing statistical significance. If p-values are less than or equal to 0.05, we reject the null hypothesis. If larger, we fail to reject.</p>
<p><strong>The significance level, <span class="math inline">\(\alpha\)</span>, is a probability used as a criterion for rejecting the null hypothesis.</strong></p>
<p>This significance level is important. In the sciences, we would rather err on the side of <em>not</em> identifying a pattern, rather than saying there is a pattern, when there it doesn’t actually exist. This concept is included in the in the discussion of *statistical errors**.</p>
<p>A Type I error is when you reject a true null hypothesis. You are saying there is a difference, when actually, if could perfectly measure your focal population, there is no difference. By establishing a significance level (<span class="math inline">\(\alpha\)</span>) of 0.05, we are saying that we are willing to accept that 5% of the time, we will say there is an effect when there isn’t one.</p>
<p>A Type II error is failing to find a pattern or a difference when there actually is one. If you reduce your <span class="math inline">\(\alpha\)</span> to reduce your likelihood of making a Type I, you increase the likelihood of committing a Type II error.</p>
<p>The probability of committing a Type II error is more challenging to quantify and is related to the concept of <strong>statistical power</strong>. A study with high <strong>power</strong> has a low likelihood of committing a Type II error. Statistical power depends on several things, including <strong>sample size</strong>, the magnitude of the <strong>effect</strong> of the treatment, and <strong>variation</strong> within the sample. A study with a LARGE sample size, a BIG treatment effect, and SMALL variation within samples will have high statistical power. We will talk about calculating statistical power later.</p>
</div>
<div id="drawing-conclusions-from-statistics" class="section level2 hasAnchor" number="1.24">
<h2><span class="header-section-number">1.24</span> Drawing conclusions from statistics<a href="index.html#drawing-conclusions-from-statistics" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In this case, we <strong>reject</strong> the null hypothesis, and state that our results <strong>support</strong> the alternative hypothesis that there is handedness in cats. Note that we ‘support’ the alternative hypothesis, rather than saying that there is pawedness in cats or accepting the alternative hypothesis. Statements about statistics are phrased to reflect that we are dealing in probabilities, and there is always a chance that our findings are incorrect. Additionally, statistical tests specifically test the null hypothesis, not the alternative (for which there are often many possibilities).</p>
<p>What would we say if we didn’t reject the null? We would state that we <strong>failed to reject</strong> the null hypothesis. Failing to reject the null indicates that our sample did not provide sufficient evidence to conclude that the effect exists, but lack of evidence doesn’t prove that the effect does not exist. For this reason, we never accept the null.</p>
</div>
<div id="reporting-results" class="section level2 hasAnchor" number="1.25">
<h2><span class="header-section-number">1.25</span> Reporting results<a href="index.html#reporting-results" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>When we report findings, we will provide:
1) A statement of findings
2) The test statistic
3) The P-value
4) A description of differences, if differences exist
5) A visualization of differences, if differences exist</p>
<p>Here, let’s focus on reporting information 1 - 3. We might say something like:
Cats displayed higher levels of handedness than expected by chance (t = 14, p = 0.031).</p>
</div>
<div id="review-problems" class="section level2 hasAnchor" number="1.26">
<h2><span class="header-section-number">1.26</span> Review problems<a href="index.html#review-problems" class="anchor-section" aria-label="Anchor link to header"></a></h2>

</div>
<div id="a-foray-into-statistics" class="section level2 hasAnchor" number="1.27">
<h2><span class="header-section-number">1.27</span> A foray into statistics<a href="index.html#a-foray-into-statistics" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Last week we talked about data types and describing data. This week we are applying concepts that we learned last week to select (and run) a statistical analysis. When conducting an analysis, a dataset will contain one or more <strong>response variables</strong> (aka y-variables, dependent variables) and one or more <strong>explanatory variables</strong> (aka x-variables, independent variables). The data types of the explanatory and response variables determine which statistical test we use.</p>
<p><strong>Brief review</strong>: Explanatory variables are used to explain variation in response variables. For instance, imagine that we want to identify areas that support high numbers of plants from the genus Mitella. We hypothesize that Mitella occurrence is positively related to water supply (i.e., the number of Mitella plants goes up as water availability increases). In this case, my response variable would be number of plants in genus Mitella, and my explanatory variable would be some measure of water supply.</p>
</div>
<div id="selecting-statistical-analyses" class="section level2 hasAnchor" number="1.28">
<h2><span class="header-section-number">1.28</span> Selecting statistical analyses<a href="index.html#selecting-statistical-analyses" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Below, you will see a very simple decision matrix for selecting statistical analyses. We will build on this basic matrix and move into alternative ways of conducting the analyses indicated within the matrix throughout the semester. However, this basic structure gives us a great launch point for structuring the next discussions. Also, the statistical analyses presented below are super common in social and ecological sciences!</p>
<p><img src="/Users/sks379/Desktop/GraduateStudents/Stats%20and%20Lit%20Review%20Lessons/Class4_SelectingStatisticalAnalyses/DecisionMatrix.png" alt="Select the statistical analysis!" />
When both the response and explanatory variables are <strong>categorical</strong>, we use what is called a <strong>G-test</strong>!</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>

<a href="structural-equation-models.html" class="navigation navigation-next navigation-unique" aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/sarasouther/DataAnalysis/edit/main/index.Rmd",
    "text": "Edit this page"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["_main.epub"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
