<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 15 Power analysis | Statistics for Ecology</title>
  <meta name="description" content="Chapter 15 Power analysis | Statistics for Ecology" />
  <meta name="generator" content="bookdown 0.43 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 15 Power analysis | Statistics for Ecology" />
  <meta property="og:type" content="book" />
  
  
  <meta name="github-repo" content="sarasouther/DataAnalysis" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 15 Power analysis | Statistics for Ecology" />
  
  
  

<meta name="author" content="Dr. Sara Souther" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="ecological-sampling.html"/>
<link rel="next" href="selecting-statistical-tests.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<link href="libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet" />
<script src="libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<script src="libs/viz-1.8.2/viz.js"></script>
<link href="libs/DiagrammeR-styles-0.2/styles.css" rel="stylesheet" />
<script src="libs/grViz-binding-1.0.11/grViz.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Statistics for Ecology</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#learning-objectives"><i class="fa fa-check"></i><b>1.1</b> Learning Objectives</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="why-statistics.html"><a href="why-statistics.html"><i class="fa fa-check"></i><b>2</b> Why Statistics?</a></li>
<li class="chapter" data-level="3" data-path="back-to-the-basics.html"><a href="back-to-the-basics.html"><i class="fa fa-check"></i><b>3</b> Back to the basics</a>
<ul>
<li class="chapter" data-level="3.1" data-path="back-to-the-basics.html"><a href="back-to-the-basics.html#what-can-statistics-tell-us"><i class="fa fa-check"></i><b>3.1</b> What can statistics tell us?</a></li>
<li class="chapter" data-level="3.2" data-path="back-to-the-basics.html"><a href="back-to-the-basics.html#the-frequentist-framework"><i class="fa fa-check"></i><b>3.2</b> The Frequentist Framework</a></li>
<li class="chapter" data-level="3.3" data-path="back-to-the-basics.html"><a href="back-to-the-basics.html#bayesian-statistics"><i class="fa fa-check"></i><b>3.3</b> Bayesian statistics</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="back-to-the-basics.html"><a href="back-to-the-basics.html#when-might-you-choose-bayesian-statistics"><i class="fa fa-check"></i><b>3.3.1</b> When might you choose Bayesian statistics?</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="back-to-the-basics.html"><a href="back-to-the-basics.html#data-types-and-why-they-matter"><i class="fa fa-check"></i><b>3.4</b> Data Types and Why They Matter</a></li>
<li class="chapter" data-level="3.5" data-path="back-to-the-basics.html"><a href="back-to-the-basics.html#linking-data-types-to-distributions"><i class="fa fa-check"></i><b>3.5</b> Linking Data Types to Distributions</a></li>
<li class="chapter" data-level="3.6" data-path="back-to-the-basics.html"><a href="back-to-the-basics.html#overview-of-common-statistical-distributions"><i class="fa fa-check"></i><b>3.6</b> Overview of Common Statistical Distributions</a>
<ul>
<li class="chapter" data-level="3.6.1" data-path="back-to-the-basics.html"><a href="back-to-the-basics.html#the-normal-distribution"><i class="fa fa-check"></i><b>3.6.1</b> The Normal Distribution</a></li>
<li class="chapter" data-level="3.6.2" data-path="back-to-the-basics.html"><a href="back-to-the-basics.html#the-binomial-distribution-outcomes-are-success-or-failure"><i class="fa fa-check"></i><b>3.6.2</b> The Binomial Distribution: Outcomes are “success” or “failure”</a></li>
<li class="chapter" data-level="3.6.3" data-path="back-to-the-basics.html"><a href="back-to-the-basics.html#the-poisson-distribution-counts-from-random-events"><i class="fa fa-check"></i><b>3.6.3</b> The Poisson Distribution: Counts from random events</a></li>
<li class="chapter" data-level="3.6.4" data-path="back-to-the-basics.html"><a href="back-to-the-basics.html#the-negative-binomial-distribution-overdispersed-counts"><i class="fa fa-check"></i><b>3.6.4</b> The Negative Binomial Distribution: Overdispersed counts</a></li>
<li class="chapter" data-level="3.6.5" data-path="back-to-the-basics.html"><a href="back-to-the-basics.html#the-uniform-distribution-all-values-equally-likely"><i class="fa fa-check"></i><b>3.6.5</b> The Uniform Distribution: All values equally likely</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="back-to-the-basics.html"><a href="back-to-the-basics.html#what-is-a-model"><i class="fa fa-check"></i><b>3.7</b> What is a model?</a></li>
<li class="chapter" data-level="3.8" data-path="back-to-the-basics.html"><a href="back-to-the-basics.html#key-takeaways"><i class="fa fa-check"></i><b>3.8</b> Key takeaways</a></li>
<li class="chapter" data-level="3.9" data-path="back-to-the-basics.html"><a href="back-to-the-basics.html#test-your-knowledge"><i class="fa fa-check"></i><b>3.9</b> Test your knowledge!</a></li>
<li class="chapter" data-level="3.10" data-path="back-to-the-basics.html"><a href="back-to-the-basics.html#assignment"><i class="fa fa-check"></i><b>3.10</b> Assignment</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="randomness-and-probability.html"><a href="randomness-and-probability.html"><i class="fa fa-check"></i><b>4</b> Randomness and probability</a>
<ul>
<li class="chapter" data-level="4.1" data-path="randomness-and-probability.html"><a href="randomness-and-probability.html#the-sample-point-method"><i class="fa fa-check"></i><b>4.1</b> The sample point method</a></li>
<li class="chapter" data-level="4.2" data-path="randomness-and-probability.html"><a href="randomness-and-probability.html#combinatorials"><i class="fa fa-check"></i><b>4.2</b> Combinatorials</a></li>
<li class="chapter" data-level="4.3" data-path="randomness-and-probability.html"><a href="randomness-and-probability.html#union-and-intersection-of-events"><i class="fa fa-check"></i><b>4.3</b> Union and intersection of events</a></li>
<li class="chapter" data-level="4.4" data-path="randomness-and-probability.html"><a href="randomness-and-probability.html#conditional-probability"><i class="fa fa-check"></i><b>4.4</b> Conditional probability</a></li>
<li class="chapter" data-level="4.5" data-path="randomness-and-probability.html"><a href="randomness-and-probability.html#multiplicative-law-of-probability-of-independent-events"><i class="fa fa-check"></i><b>4.5</b> Multiplicative Law of Probability of Independent Events</a></li>
<li class="chapter" data-level="4.6" data-path="randomness-and-probability.html"><a href="randomness-and-probability.html#additive-law-of-probability-of-mutually-exclusive-events"><i class="fa fa-check"></i><b>4.6</b> Additive Law of Probability of Mutually Exclusive Events</a></li>
<li class="chapter" data-level="4.7" data-path="randomness-and-probability.html"><a href="randomness-and-probability.html#general-additive-law-of-probability"><i class="fa fa-check"></i><b>4.7</b> General Additive Law of Probability</a></li>
<li class="chapter" data-level="4.8" data-path="randomness-and-probability.html"><a href="randomness-and-probability.html#key-concepts"><i class="fa fa-check"></i><b>4.8</b> Key concepts</a></li>
<li class="chapter" data-level="4.9" data-path="randomness-and-probability.html"><a href="randomness-and-probability.html#practice-problems"><i class="fa fa-check"></i><b>4.9</b> Practice problems</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="expected-value-of-a-fair-die-roll.html"><a href="expected-value-of-a-fair-die-roll.html"><i class="fa fa-check"></i><b>5</b> Expected value of a fair die roll</a></li>
<li class="chapter" data-level="6" data-path="variance-of-a-fair-die-roll.html"><a href="variance-of-a-fair-die-roll.html"><i class="fa fa-check"></i><b>6</b> Variance of a fair die roll</a></li>
<li class="chapter" data-level="7" data-path="take-many-samples-and-calculate-means.html"><a href="take-many-samples-and-calculate-means.html"><i class="fa fa-check"></i><b>7</b> Take many samples and calculate means</a></li>
<li class="chapter" data-level="8" data-path="uniform-population.html"><a href="uniform-population.html"><i class="fa fa-check"></i><b>8</b> Uniform population</a></li>
<li class="chapter" data-level="9" data-path="exponential-population-highly-skewed.html"><a href="exponential-population-highly-skewed.html"><i class="fa fa-check"></i><b>9</b> Exponential population (highly skewed)</a></li>
<li class="chapter" data-level="10" data-path="ppositive-pposdiseasepdisease-pposno-diseasepno-disease.html"><a href="ppositive-pposdiseasepdisease-pposno-diseasepno-disease.html"><i class="fa fa-check"></i><b>10</b> P(positive) = P(pos|disease)<em>P(disease) + P(pos|no disease)</em>P(no disease)</a></li>
<li class="chapter" data-level="11" data-path="pdisease-positive-pposdisease-pdisease-ppositive.html"><a href="pdisease-positive-pposdisease-pdisease-ppositive.html"><i class="fa fa-check"></i><b>11</b> P(disease | positive) = P(pos|disease) * P(disease) / P(positive)</a></li>
<li class="chapter" data-level="12" data-path="probability-of-9-or-10-heads-in-10-flips-of-fair-coin.html"><a href="probability-of-9-or-10-heads-in-10-flips-of-fair-coin.html"><i class="fa fa-check"></i><b>12</b> Probability of 9 or 10 heads in 10 flips of fair coin</a></li>
<li class="chapter" data-level="13" data-path="data-exploration-and-assumption-checking.html"><a href="data-exploration-and-assumption-checking.html"><i class="fa fa-check"></i><b>13</b> Data Exploration and Assumption Checking</a></li>
<li class="chapter" data-level="14" data-path="ecological-sampling.html"><a href="ecological-sampling.html"><i class="fa fa-check"></i><b>14</b> Ecological sampling</a>
<ul>
<li class="chapter" data-level="14.1" data-path="ecological-sampling.html"><a href="ecological-sampling.html#background"><i class="fa fa-check"></i><b>14.1</b> Background</a></li>
<li class="chapter" data-level="14.2" data-path="ecological-sampling.html"><a href="ecological-sampling.html#sampling-approaches"><i class="fa fa-check"></i><b>14.2</b> Sampling approaches</a>
<ul>
<li class="chapter" data-level="14.2.1" data-path="ecological-sampling.html"><a href="ecological-sampling.html#random-sampling"><i class="fa fa-check"></i><b>14.2.1</b> Random sampling</a></li>
<li class="chapter" data-level="14.2.2" data-path="ecological-sampling.html"><a href="ecological-sampling.html#stratified-random-sampling"><i class="fa fa-check"></i><b>14.2.2</b> Stratified random sampling</a></li>
<li class="chapter" data-level="14.2.3" data-path="ecological-sampling.html"><a href="ecological-sampling.html#gridded-random-sampling"><i class="fa fa-check"></i><b>14.2.3</b> Gridded random sampling</a></li>
<li class="chapter" data-level="14.2.4" data-path="ecological-sampling.html"><a href="ecological-sampling.html#random-cluster-sampling"><i class="fa fa-check"></i><b>14.2.4</b> Random cluster sampling</a></li>
<li class="chapter" data-level="14.2.5" data-path="ecological-sampling.html"><a href="ecological-sampling.html#grts-sampling-generalized-random-tessellation-stratified-sampling"><i class="fa fa-check"></i><b>14.2.5</b> GRTS Sampling (Generalized Random-Tessellation Stratified Sampling)</a></li>
<li class="chapter" data-level="14.2.6" data-path="ecological-sampling.html"><a href="ecological-sampling.html#understanding-design-weights"><i class="fa fa-check"></i><b>14.2.6</b> Understanding Design Weights</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="ecological-sampling.html"><a href="ecological-sampling.html#systematic-sampling"><i class="fa fa-check"></i><b>14.3</b> Systematic Sampling</a></li>
<li class="chapter" data-level="14.4" data-path="ecological-sampling.html"><a href="ecological-sampling.html#adaptive-sampling-sampling-rare-or-patchy-species"><i class="fa fa-check"></i><b>14.4</b> Adaptive Sampling (Sampling Rare or Patchy Species)</a></li>
<li class="chapter" data-level="14.5" data-path="ecological-sampling.html"><a href="ecological-sampling.html#imperfect-detection-in-ecological-sampling"><i class="fa fa-check"></i><b>14.5</b> Imperfect Detection in Ecological Sampling</a></li>
<li class="chapter" data-level="14.6" data-path="ecological-sampling.html"><a href="ecological-sampling.html#temporal-sampling-and-study-designs-through-time"><i class="fa fa-check"></i><b>14.6</b> Temporal Sampling and Study Designs Through Time</a>
<ul>
<li class="chapter" data-level="14.6.1" data-path="ecological-sampling.html"><a href="ecological-sampling.html#sampling-panels"><i class="fa fa-check"></i><b>14.6.1</b> Sampling Panels</a></li>
<li class="chapter" data-level="14.6.2" data-path="ecological-sampling.html"><a href="ecological-sampling.html#baci-designs-beforeaftercontrolimpact"><i class="fa fa-check"></i><b>14.6.2</b> BACI Designs (Before–After–Control–Impact)</a></li>
</ul></li>
<li class="chapter" data-level="14.7" data-path="ecological-sampling.html"><a href="ecological-sampling.html#plot-shapes-sizes-and-transects"><i class="fa fa-check"></i><b>14.7</b> Plot shapes, sizes, and transects</a></li>
<li class="chapter" data-level="14.8" data-path="ecological-sampling.html"><a href="ecological-sampling.html#distance-sampling-and-point-counts"><i class="fa fa-check"></i><b>14.8</b> Distance Sampling and Point Counts</a></li>
<li class="chapter" data-level="14.9" data-path="ecological-sampling.html"><a href="ecological-sampling.html#reducing-sampling-error"><i class="fa fa-check"></i><b>14.9</b> Reducing sampling error</a></li>
<li class="chapter" data-level="14.10" data-path="ecological-sampling.html"><a href="ecological-sampling.html#sample-size-determination-in-ecology-effect-sizes-and-precision"><i class="fa fa-check"></i><b>14.10</b> Sample Size Determination in Ecology: Effect Sizes and Precision</a></li>
<li class="chapter" data-level="14.11" data-path="ecological-sampling.html"><a href="ecological-sampling.html#variables-of-interest"><i class="fa fa-check"></i><b>14.11</b> Variables of interest</a></li>
<li class="chapter" data-level="14.12" data-path="ecological-sampling.html"><a href="ecological-sampling.html#test-your-knowledge-1"><i class="fa fa-check"></i><b>14.12</b> Test your knowledge</a></li>
<li class="chapter" data-level="14.13" data-path="ecological-sampling.html"><a href="ecological-sampling.html#assignment-1"><i class="fa fa-check"></i><b>14.13</b> Assignment</a>
<ul>
<li class="chapter" data-level="14.13.1" data-path="ecological-sampling.html"><a href="ecological-sampling.html#example-methods-sampling-design"><i class="fa fa-check"></i><b>14.13.1</b> Example Methods: Sampling Design</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="15" data-path="power-analysis.html"><a href="power-analysis.html"><i class="fa fa-check"></i><b>15</b> Power analysis</a>
<ul>
<li class="chapter" data-level="15.1" data-path="power-analysis.html"><a href="power-analysis.html#prework"><i class="fa fa-check"></i><b>15.1</b> Prework</a></li>
<li class="chapter" data-level="15.2" data-path="power-analysis.html"><a href="power-analysis.html#statistical-power"><i class="fa fa-check"></i><b>15.2</b> Statistical power</a></li>
<li class="chapter" data-level="15.3" data-path="power-analysis.html"><a href="power-analysis.html#describing-data"><i class="fa fa-check"></i><b>15.3</b> Describing data</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="selecting-statistical-tests.html"><a href="selecting-statistical-tests.html"><i class="fa fa-check"></i><b>16</b> Selecting statistical tests</a>
<ul>
<li class="chapter" data-level="16.1" data-path="selecting-statistical-tests.html"><a href="selecting-statistical-tests.html#a-foray-into-statistics"><i class="fa fa-check"></i><b>16.1</b> A foray into statistics</a></li>
<li class="chapter" data-level="16.2" data-path="selecting-statistical-tests.html"><a href="selecting-statistical-tests.html#pick-the-explanatory-and-response-variable"><i class="fa fa-check"></i><b>16.2</b> Pick the explanatory and response variable</a></li>
<li class="chapter" data-level="16.3" data-path="selecting-statistical-tests.html"><a href="selecting-statistical-tests.html#variable-types-refresher"><i class="fa fa-check"></i><b>16.3</b> Variable types refresher</a></li>
<li class="chapter" data-level="16.4" data-path="selecting-statistical-tests.html"><a href="selecting-statistical-tests.html#more-examples"><i class="fa fa-check"></i><b>16.4</b> More examples</a></li>
<li class="chapter" data-level="16.5" data-path="selecting-statistical-tests.html"><a href="selecting-statistical-tests.html#the-decision-matrix"><i class="fa fa-check"></i><b>16.5</b> The decision matrix</a></li>
<li class="chapter" data-level="16.6" data-path="selecting-statistical-tests.html"><a href="selecting-statistical-tests.html#a-note-on-assumptions"><i class="fa fa-check"></i><b>16.6</b> A note on assumptions</a></li>
<li class="chapter" data-level="16.7" data-path="selecting-statistical-tests.html"><a href="selecting-statistical-tests.html#learning-goals"><i class="fa fa-check"></i><b>16.7</b> Learning goals</a></li>
<li class="chapter" data-level="16.8" data-path="selecting-statistical-tests.html"><a href="selecting-statistical-tests.html#downloads-for-this-class"><i class="fa fa-check"></i><b>16.8</b> Downloads for this class</a></li>
<li class="chapter" data-level="16.9" data-path="selecting-statistical-tests.html"><a href="selecting-statistical-tests.html#in-class-practice"><i class="fa fa-check"></i><b>16.9</b> In-class practice</a></li>
<li class="chapter" data-level="16.10" data-path="selecting-statistical-tests.html"><a href="selecting-statistical-tests.html#assignment-choosing-and-running-the-right-test"><i class="fa fa-check"></i><b>16.10</b> Assignment: Choosing and Running the Right Test</a>
<ul>
<li class="chapter" data-level="16.10.1" data-path="selecting-statistical-tests.html"><a href="selecting-statistical-tests.html#deliverables"><i class="fa fa-check"></i><b>16.10.1</b> Deliverables</a></li>
</ul></li>
<li class="chapter" data-level="16.11" data-path="selecting-statistical-tests.html"><a href="selecting-statistical-tests.html#statistical-analyses-for-your-species-interaction-lab"><i class="fa fa-check"></i><b>16.11</b> Statistical analyses for your species interaction lab</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="basic-statistical-testing.html"><a href="basic-statistical-testing.html"><i class="fa fa-check"></i><b>17</b> Basic statistical testing</a>
<ul>
<li class="chapter" data-level="17.1" data-path="basic-statistical-testing.html"><a href="basic-statistical-testing.html#a-short-statistical-review"><i class="fa fa-check"></i><b>17.1</b> A short statistical review</a>
<ul>
<li class="chapter" data-level="17.1.1" data-path="basic-statistical-testing.html"><a href="basic-statistical-testing.html#what-can-statistics-tell-us-1"><i class="fa fa-check"></i><b>17.1.1</b> What can statistics tell us?</a></li>
<li class="chapter" data-level="17.1.2" data-path="basic-statistical-testing.html"><a href="basic-statistical-testing.html#sampling-populations"><i class="fa fa-check"></i><b>17.1.2</b> Sampling populations</a></li>
</ul></li>
<li class="chapter" data-level="17.2" data-path="basic-statistical-testing.html"><a href="basic-statistical-testing.html#hypothesis-testing-review"><i class="fa fa-check"></i><b>17.2</b> Hypothesis testing review</a></li>
<li class="chapter" data-level="17.3" data-path="basic-statistical-testing.html"><a href="basic-statistical-testing.html#downloads-for-this-module"><i class="fa fa-check"></i><b>17.3</b> Downloads for this module</a></li>
<li class="chapter" data-level="17.4" data-path="basic-statistical-testing.html"><a href="basic-statistical-testing.html#objectives"><i class="fa fa-check"></i><b>17.4</b> Objectives</a></li>
<li class="chapter" data-level="17.5" data-path="basic-statistical-testing.html"><a href="basic-statistical-testing.html#tailed-tests"><i class="fa fa-check"></i><b>17.5</b> Tailed tests</a>
<ul>
<li class="chapter" data-level="17.5.1" data-path="basic-statistical-testing.html"><a href="basic-statistical-testing.html#generate-hypotheses"><i class="fa fa-check"></i><b>17.5.1</b> Generate hypotheses</a></li>
<li class="chapter" data-level="17.5.2" data-path="basic-statistical-testing.html"><a href="basic-statistical-testing.html#calculate-a-test-statistic"><i class="fa fa-check"></i><b>17.5.2</b> Calculate a test statistic</a></li>
<li class="chapter" data-level="17.5.3" data-path="basic-statistical-testing.html"><a href="basic-statistical-testing.html#determine-the-p-value"><i class="fa fa-check"></i><b>17.5.3</b> Determine the p-value</a></li>
</ul></li>
<li class="chapter" data-level="17.6" data-path="basic-statistical-testing.html"><a href="basic-statistical-testing.html#drawing-conclusions-from-statistics"><i class="fa fa-check"></i><b>17.6</b> Drawing conclusions from statistics</a></li>
<li class="chapter" data-level="17.7" data-path="basic-statistical-testing.html"><a href="basic-statistical-testing.html#reporting-results"><i class="fa fa-check"></i><b>17.7</b> Reporting results</a></li>
<li class="chapter" data-level="17.8" data-path="basic-statistical-testing.html"><a href="basic-statistical-testing.html#assignment-2"><i class="fa fa-check"></i><b>17.8</b> Assignment</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="generalized-linear-models-glms.html"><a href="generalized-linear-models-glms.html"><i class="fa fa-check"></i><b>18</b> Generalized Linear Models (GLMs)</a>
<ul>
<li class="chapter" data-level="18.1" data-path="generalized-linear-models-glms.html"><a href="generalized-linear-models-glms.html#linear-models"><i class="fa fa-check"></i><b>18.1</b> Linear models</a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html"><i class="fa fa-check"></i><b>19</b> Generalized Linear Models</a>
<ul>
<li class="chapter" data-level="19.1" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#link-functions"><i class="fa fa-check"></i><b>19.1</b> Link functions</a></li>
<li class="chapter" data-level="19.2" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#glms-in-r"><i class="fa fa-check"></i><b>19.2</b> GLMs in R</a></li>
</ul></li>
<li class="chapter" data-level="20" data-path="mixed-effects-models.html"><a href="mixed-effects-models.html"><i class="fa fa-check"></i><b>20</b> Mixed Effects Models</a>
<ul>
<li class="chapter" data-level="20.1" data-path="mixed-effects-models.html"><a href="mixed-effects-models.html#examples-in-r"><i class="fa fa-check"></i><b>20.1</b> Examples in R</a></li>
</ul></li>
<li class="chapter" data-level="21" data-path="before-after-control-impact.html"><a href="before-after-control-impact.html"><i class="fa fa-check"></i><b>21</b> Before-After-Control-Impact</a>
<ul>
<li class="chapter" data-level="21.1" data-path="before-after-control-impact.html"><a href="before-after-control-impact.html#which-design"><i class="fa fa-check"></i><b>21.1</b> Which design</a></li>
<li class="chapter" data-level="21.2" data-path="before-after-control-impact.html"><a href="before-after-control-impact.html#baci-design-2"><i class="fa fa-check"></i><b>21.2</b> BACI Design 2</a></li>
</ul></li>
<li class="chapter" data-level="22" data-path="time-is-a-flat-circle.html"><a href="time-is-a-flat-circle.html"><i class="fa fa-check"></i><b>22</b> Time is a flat circle</a></li>
<li class="chapter" data-level="23" data-path="describing-ecological-patterns.html"><a href="describing-ecological-patterns.html"><i class="fa fa-check"></i><b>23</b> Describing ecological patterns</a>
<ul>
<li class="chapter" data-level="23.1" data-path="describing-ecological-patterns.html"><a href="describing-ecological-patterns.html#when-to-use-model-selection"><i class="fa fa-check"></i><b>23.1</b> When to use model selection?</a></li>
<li class="chapter" data-level="23.2" data-path="describing-ecological-patterns.html"><a href="describing-ecological-patterns.html#step-1-identifying-predictor-variables-or-co-variates-of-importance"><i class="fa fa-check"></i><b>23.2</b> Step 1: Identifying predictor variables or co-variates of importance</a></li>
<li class="chapter" data-level="23.3" data-path="describing-ecological-patterns.html"><a href="describing-ecological-patterns.html#step-2-removing-colinear-variables"><i class="fa fa-check"></i><b>23.3</b> Step 2: Removing colinear variables</a>
<ul>
<li class="chapter" data-level="23.3.1" data-path="describing-ecological-patterns.html"><a href="describing-ecological-patterns.html#automated-variable-removal"><i class="fa fa-check"></i><b>23.3.1</b> Automated Variable Removal</a></li>
<li class="chapter" data-level="23.3.2" data-path="describing-ecological-patterns.html"><a href="describing-ecological-patterns.html#expert-knowledge-driven-selection"><i class="fa fa-check"></i><b>23.3.2</b> Expert Knowledge-Driven Selection</a></li>
<li class="chapter" data-level="23.3.3" data-path="describing-ecological-patterns.html"><a href="describing-ecological-patterns.html#blended-strategy-recommended"><i class="fa fa-check"></i><b>23.3.3</b> Blended Strategy (Recommended)</a></li>
</ul></li>
<li class="chapter" data-level="23.4" data-path="describing-ecological-patterns.html"><a href="describing-ecological-patterns.html#example-reducing-colinear-climate-variables"><i class="fa fa-check"></i><b>23.4</b> Example: Reducing colinear climate variables</a></li>
<li class="chapter" data-level="23.5" data-path="describing-ecological-patterns.html"><a href="describing-ecological-patterns.html#step-3-select-the-best-model"><i class="fa fa-check"></i><b>23.5</b> Step 3: Select the best model</a>
<ul>
<li class="chapter" data-level="23.5.1" data-path="describing-ecological-patterns.html"><a href="describing-ecological-patterns.html#major-types-of-model-selection-overview-benefits-drawbacks-and-applications"><i class="fa fa-check"></i><b>23.5.1</b> Major Types of Model Selection: Overview, Benefits, Drawbacks, and Applications</a></li>
<li class="chapter" data-level="23.5.2" data-path="describing-ecological-patterns.html"><a href="describing-ecological-patterns.html#stepwise-regression-based-on-aic-akaike-information-criterion."><i class="fa fa-check"></i><b>23.5.2</b> Stepwise regression based on AIC (Akaike Information Criterion).</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="24" data-path="plot-establishment.html"><a href="plot-establishment.html"><i class="fa fa-check"></i><b>24</b> Plot establishment</a></li>
<li class="chapter" data-level="25" data-path="bootstrapping-and-resampling.html"><a href="bootstrapping-and-resampling.html"><i class="fa fa-check"></i><b>25</b> Bootstrapping and resampling</a></li>
<li class="chapter" data-level="26" data-path="population-sensation.html"><a href="population-sensation.html"><i class="fa fa-check"></i><b>26</b> Population sensation</a>
<ul>
<li class="chapter" data-level="26.1" data-path="population-sensation.html"><a href="population-sensation.html#population-characteristics"><i class="fa fa-check"></i><b>26.1</b> Population characteristics</a></li>
<li class="chapter" data-level="26.2" data-path="population-sensation.html"><a href="population-sensation.html#planning-a-census"><i class="fa fa-check"></i><b>26.2</b> Planning a census</a></li>
<li class="chapter" data-level="26.3" data-path="population-sensation.html"><a href="population-sensation.html#life-cycle-diagrams"><i class="fa fa-check"></i><b>26.3</b> Life cycle diagrams</a></li>
<li class="chapter" data-level="26.4" data-path="population-sensation.html"><a href="population-sensation.html#population-demographic-models"><i class="fa fa-check"></i><b>26.4</b> Population demographic models</a></li>
<li class="chapter" data-level="26.5" data-path="population-sensation.html"><a href="population-sensation.html#integral-projection-models"><i class="fa fa-check"></i><b>26.5</b> Integral projection models</a></li>
<li class="chapter" data-level="26.6" data-path="population-sensation.html"><a href="population-sensation.html#an-example-population-ecology-of-an-endangered-plant"><i class="fa fa-check"></i><b>26.6</b> An example: Population ecology of an endangered plant</a></li>
<li class="chapter" data-level="26.7" data-path="population-sensation.html"><a href="population-sensation.html#putting-it-all-together"><i class="fa fa-check"></i><b>26.7</b> Putting it all together</a></li>
<li class="chapter" data-level="26.8" data-path="population-sensation.html"><a href="population-sensation.html#generating-confidence-intervals"><i class="fa fa-check"></i><b>26.8</b> Generating confidence intervals</a></li>
<li class="chapter" data-level="26.9" data-path="population-sensation.html"><a href="population-sensation.html#different-life-histories"><i class="fa fa-check"></i><b>26.9</b> Different life histories</a></li>
</ul></li>
<li class="chapter" data-level="27" data-path="permuting-your-brains-out.html"><a href="permuting-your-brains-out.html"><i class="fa fa-check"></i><b>27</b> Permuting your brains out</a></li>
<li class="chapter" data-level="28" data-path="spatial-data.html"><a href="spatial-data.html"><i class="fa fa-check"></i><b>28</b> Spatial data</a></li>
<li class="chapter" data-level="29" data-path="read.html"><a href="read.html"><i class="fa fa-check"></i><b>29</b> Read</a></li>
<li class="chapter" data-level="30" data-path="check-structure.html"><a href="check-structure.html"><i class="fa fa-check"></i><b>30</b> Check structure</a></li>
<li class="chapter" data-level="31" data-path="write.html"><a href="write.html"><i class="fa fa-check"></i><b>31</b> Write</a></li>
<li class="chapter" data-level="32" data-path="read-1.html"><a href="read-1.html"><i class="fa fa-check"></i><b>32</b> Read</a></li>
<li class="chapter" data-level="33" data-path="check-properties.html"><a href="check-properties.html"><i class="fa fa-check"></i><b>33</b> Check properties</a></li>
<li class="chapter" data-level="34" data-path="write-1.html"><a href="write-1.html"><i class="fa fa-check"></i><b>34</b> Write</a></li>
<li class="chapter" data-level="35" data-path="create-neighbor-list.html"><a href="create-neighbor-list.html"><i class="fa fa-check"></i><b>35</b> Create neighbor list</a></li>
<li class="chapter" data-level="36" data-path="test-residuals.html"><a href="test-residuals.html"><i class="fa fa-check"></i><b>36</b> Test residuals</a></li>
<li class="chapter" data-level="37" data-path="species-distribution-modeling.html"><a href="species-distribution-modeling.html"><i class="fa fa-check"></i><b>37</b> Species Distribution Modeling</a>
<ul>
<li class="chapter" data-level="37.1" data-path="species-distribution-modeling.html"><a href="species-distribution-modeling.html#introduction-1"><i class="fa fa-check"></i><b>37.1</b> Introduction</a></li>
<li class="chapter" data-level="37.2" data-path="species-distribution-modeling.html"><a href="species-distribution-modeling.html#a-brief-review-of-niche-theory"><i class="fa fa-check"></i><b>37.2</b> A brief review of niche theory</a></li>
<li class="chapter" data-level="37.3" data-path="species-distribution-modeling.html"><a href="species-distribution-modeling.html#downloads-for-this-lab"><i class="fa fa-check"></i><b>37.3</b> Downloads for this lab</a></li>
<li class="chapter" data-level="37.4" data-path="species-distribution-modeling.html"><a href="species-distribution-modeling.html#objectives-1"><i class="fa fa-check"></i><b>37.4</b> Objectives</a></li>
<li class="chapter" data-level="37.5" data-path="species-distribution-modeling.html"><a href="species-distribution-modeling.html#methods"><i class="fa fa-check"></i><b>37.5</b> Methods</a>
<ul>
<li class="chapter" data-level="37.5.1" data-path="species-distribution-modeling.html"><a href="species-distribution-modeling.html#lets-get-modeling"><i class="fa fa-check"></i><b>37.5.1</b> Let’s get modeling</a></li>
<li class="chapter" data-level="37.5.2" data-path="species-distribution-modeling.html"><a href="species-distribution-modeling.html#run-the-r-code"><i class="fa fa-check"></i><b>37.5.2</b> Run the R code</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="38" data-path="diversity-statistics.html"><a href="diversity-statistics.html"><i class="fa fa-check"></i><b>38</b> Diversity statistics</a>
<ul>
<li class="chapter" data-level="38.1" data-path="diversity-statistics.html"><a href="diversity-statistics.html#inext"><i class="fa fa-check"></i><b>38.1</b> iNext</a></li>
<li class="chapter" data-level="38.2" data-path="diversity-statistics.html"><a href="diversity-statistics.html#coveragebased-re-sampling-curves"><i class="fa fa-check"></i><b>38.2</b> Coverage‐based R/E sampling curves</a></li>
<li class="chapter" data-level="38.3" data-path="diversity-statistics.html"><a href="diversity-statistics.html#data-manipulation"><i class="fa fa-check"></i><b>38.3</b> Data manipulation</a></li>
</ul></li>
<li class="chapter" data-level="39" data-path="ordination-station.html"><a href="ordination-station.html"><i class="fa fa-check"></i><b>39</b> Ordination station</a></li>
<li class="chapter" data-level="40" data-path="what-are-structural-equation-models.html"><a href="what-are-structural-equation-models.html"><i class="fa fa-check"></i><b>40</b> What are structural equation models?</a>
<ul>
<li class="chapter" data-level="40.0.1" data-path="what-are-structural-equation-models.html"><a href="what-are-structural-equation-models.html#when-should-you-use-sem"><i class="fa fa-check"></i><b>40.0.1</b> When Should You Use SEM?</a></li>
<li class="chapter" data-level="40.0.2" data-path="what-are-structural-equation-models.html"><a href="what-are-structural-equation-models.html#how-is-sem-different-from-multiple-regression"><i class="fa fa-check"></i><b>40.0.2</b> How is SEM Different from Multiple Regression?</a></li>
<li class="chapter" data-level="40.0.3" data-path="what-are-structural-equation-models.html"><a href="what-are-structural-equation-models.html#summary"><i class="fa fa-check"></i><b>40.0.3</b> Summary</a></li>
<li class="chapter" data-level="40.1" data-path="what-are-structural-equation-models.html"><a href="what-are-structural-equation-models.html#anatomy-of-a-structural-equation-model"><i class="fa fa-check"></i><b>40.1</b> Anatomy of a Structural Equation Model</a>
<ul>
<li class="chapter" data-level="40.1.1" data-path="what-are-structural-equation-models.html"><a href="what-are-structural-equation-models.html#types-of-variables"><i class="fa fa-check"></i><b>40.1.1</b> Types of Variables</a></li>
<li class="chapter" data-level="40.1.2" data-path="what-are-structural-equation-models.html"><a href="what-are-structural-equation-models.html#path-diagrams"><i class="fa fa-check"></i><b>40.1.2</b> Path Diagrams</a></li>
</ul></li>
<li class="chapter" data-level="40.2" data-path="what-are-structural-equation-models.html"><a href="what-are-structural-equation-models.html#building-multivariate-models"><i class="fa fa-check"></i><b>40.2</b> Building Multivariate Models</a>
<ul>
<li class="chapter" data-level="40.2.1" data-path="what-are-structural-equation-models.html"><a href="what-are-structural-equation-models.html#what-is-causality"><i class="fa fa-check"></i><b>40.2.1</b> What is Causality?</a></li>
<li class="chapter" data-level="40.2.2" data-path="what-are-structural-equation-models.html"><a href="what-are-structural-equation-models.html#why-move-beyond-multiple-regression"><i class="fa fa-check"></i><b>40.2.2</b> Why move beyond Multiple Regression?</a></li>
<li class="chapter" data-level="40.2.3" data-path="what-are-structural-equation-models.html"><a href="what-are-structural-equation-models.html#meta-modeling-your-system"><i class="fa fa-check"></i><b>40.2.3</b> Meta-Modeling Your System</a></li>
</ul></li>
<li class="chapter" data-level="40.3" data-path="what-are-structural-equation-models.html"><a href="what-are-structural-equation-models.html#from-concept-to-model"><i class="fa fa-check"></i><b>40.3</b> From Concept to Model</a></li>
<li class="chapter" data-level="40.4" data-path="what-are-structural-equation-models.html"><a href="what-are-structural-equation-models.html#common-structures-in-causal-diagrams"><i class="fa fa-check"></i><b>40.4</b> Common Structures in Causal Diagrams</a>
<ul>
<li class="chapter" data-level="40.4.1" data-path="what-are-structural-equation-models.html"><a href="what-are-structural-equation-models.html#chains-mediation-paths"><i class="fa fa-check"></i><b>40.4.1</b> Chains (Mediation Paths)</a></li>
<li class="chapter" data-level="40.4.2" data-path="what-are-structural-equation-models.html"><a href="what-are-structural-equation-models.html#colliders"><i class="fa fa-check"></i><b>40.4.2</b> Colliders</a></li>
<li class="chapter" data-level="40.4.3" data-path="what-are-structural-equation-models.html"><a href="what-are-structural-equation-models.html#forks-confounding-paths"><i class="fa fa-check"></i><b>40.4.3</b> Forks (Confounding Paths)</a></li>
<li class="chapter" data-level="40.4.4" data-path="what-are-structural-equation-models.html"><a href="what-are-structural-equation-models.html#descendants-of-colliders"><i class="fa fa-check"></i><b>40.4.4</b> Descendants of Colliders</a></li>
<li class="chapter" data-level="40.4.5" data-path="what-are-structural-equation-models.html"><a href="what-are-structural-equation-models.html#summary-of-strcutures"><i class="fa fa-check"></i><b>40.4.5</b> Summary of strcutures</a></li>
<li class="chapter" data-level="40.4.6" data-path="what-are-structural-equation-models.html"><a href="what-are-structural-equation-models.html#identifying-causality"><i class="fa fa-check"></i><b>40.4.6</b> Identifying Causality</a></li>
<li class="chapter" data-level="40.4.7" data-path="what-are-structural-equation-models.html"><a href="what-are-structural-equation-models.html#backdoor-criterion"><i class="fa fa-check"></i><b>40.4.7</b> Backdoor Criterion</a></li>
<li class="chapter" data-level="40.4.8" data-path="what-are-structural-equation-models.html"><a href="what-are-structural-equation-models.html#frontdoor-criterion"><i class="fa fa-check"></i><b>40.4.8</b> Frontdoor Criterion</a></li>
<li class="chapter" data-level="40.4.9" data-path="what-are-structural-equation-models.html"><a href="what-are-structural-equation-models.html#build-your-own-dag-sem-case-study-on-pollinator-impacts-of-vegetation-management"><i class="fa fa-check"></i><b>40.4.9</b> Build your own DAG: SEM Case Study on Pollinator Impacts of Vegetation Management</a></li>
<li class="chapter" data-level="40.4.10" data-path="what-are-structural-equation-models.html"><a href="what-are-structural-equation-models.html#adjustment-sets"><i class="fa fa-check"></i><b>40.4.10</b> Adjustment Sets</a></li>
</ul></li>
<li class="chapter" data-level="40.5" data-path="what-are-structural-equation-models.html"><a href="what-are-structural-equation-models.html#chapter-5-covariance-based-estimation-in-sem"><i class="fa fa-check"></i><b>40.5</b> Chapter 5: Covariance-Based Estimation in SEM</a>
<ul>
<li class="chapter" data-level="40.5.1" data-path="what-are-structural-equation-models.html"><a href="what-are-structural-equation-models.html#what-is-covariance-based-sem"><i class="fa fa-check"></i><b>40.5.1</b> What is Covariance-Based SEM?</a></li>
<li class="chapter" data-level="40.5.2" data-path="what-are-structural-equation-models.html"><a href="what-are-structural-equation-models.html#maximum-likelihood-estimation"><i class="fa fa-check"></i><b>40.5.2</b> Maximum Likelihood Estimation</a></li>
<li class="chapter" data-level="40.5.3" data-path="what-are-structural-equation-models.html"><a href="what-are-structural-equation-models.html#assumptions-behind-ml-estimation"><i class="fa fa-check"></i><b>40.5.3</b> Assumptions Behind ML Estimation</a></li>
<li class="chapter" data-level="40.5.4" data-path="what-are-structural-equation-models.html"><a href="what-are-structural-equation-models.html#identifiability"><i class="fa fa-check"></i><b>40.5.4</b> Identifiability</a></li>
<li class="chapter" data-level="40.5.5" data-path="what-are-structural-equation-models.html"><a href="what-are-structural-equation-models.html#degrees-of-freedom"><i class="fa fa-check"></i><b>40.5.5</b> Degrees of Freedom</a></li>
<li class="chapter" data-level="40.5.6" data-path="what-are-structural-equation-models.html"><a href="what-are-structural-equation-models.html#sample-size-considerations"><i class="fa fa-check"></i><b>40.5.6</b> Sample Size Considerations</a></li>
<li class="chapter" data-level="40.5.7" data-path="what-are-structural-equation-models.html"><a href="what-are-structural-equation-models.html#summary-1"><i class="fa fa-check"></i><b>40.5.7</b> Summary</a></li>
<li class="chapter" data-level="40.5.8" data-path="what-are-structural-equation-models.html"><a href="what-are-structural-equation-models.html#chapter-6-structural-equation-modeling-in-r-with-lavaan"><i class="fa fa-check"></i><b>40.5.8</b> Chapter 6: Structural Equation Modeling in R with lavaan</a></li>
</ul></li>
<li class="chapter" data-level="40.6" data-path="what-are-structural-equation-models.html"><a href="what-are-structural-equation-models.html#getting-started-with-lavaan-model-specification-estimation-and-interpretation"><i class="fa fa-check"></i><b>40.6</b> Getting Started with lavaan – Model Specification, Estimation, and Interpretation</a>
<ul>
<li class="chapter" data-level="40.6.1" data-path="what-are-structural-equation-models.html"><a href="what-are-structural-equation-models.html#chapter-7assessing-fit-and-normality"><i class="fa fa-check"></i><b>40.6.1</b> Chapter 7:Assessing Fit and Normality</a></li>
<li class="chapter" data-level="40.6.2" data-path="what-are-structural-equation-models.html"><a href="what-are-structural-equation-models.html#chapter-8-comparing-models-and-testing-mediation"><i class="fa fa-check"></i><b>40.6.2</b> Chapter 8: Comparing Models and Testing Mediation</a></li>
<li class="chapter" data-level="40.6.3" data-path="what-are-structural-equation-models.html"><a href="what-are-structural-equation-models.html#chapter-8-latent-variables-as-drivers"><i class="fa fa-check"></i><b>40.6.3</b> Chapter 8: Latent Variables as Drivers</a></li>
<li class="chapter" data-level="40.6.4" data-path="what-are-structural-equation-models.html"><a href="what-are-structural-equation-models.html#chapter-10-latent-responses-and-measurement-error"><i class="fa fa-check"></i><b>40.6.4</b> Chapter 10: Latent Responses and Measurement Error</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="41" data-path="piecewise-sems.html"><a href="piecewise-sems.html"><i class="fa fa-check"></i><b>41</b> Piecewise SEMs</a>
<ul>
<li class="chapter" data-level="41.1" data-path="piecewise-sems.html"><a href="piecewise-sems.html#overview"><i class="fa fa-check"></i><b>41.1</b> Overview</a></li>
<li class="chapter" data-level="41.2" data-path="piecewise-sems.html"><a href="piecewise-sems.html#why-use-piecewise-sem-instead-of-a-covariance-sem"><i class="fa fa-check"></i><b>41.2</b> Why Use Piecewise SEM, instead of a covariance SEM?</a>
<ul>
<li class="chapter" data-level="41.2.1" data-path="piecewise-sems.html"><a href="piecewise-sems.html#comparison-of-sem-approaches"><i class="fa fa-check"></i><b>41.2.1</b> Comparison of SEM Approaches</a></li>
<li class="chapter" data-level="41.2.2" data-path="piecewise-sems.html"><a href="piecewise-sems.html#benefits-of-covariance-based-sem"><i class="fa fa-check"></i><b>41.2.2</b> Benefits of Covariance-Based SEM</a></li>
<li class="chapter" data-level="41.2.3" data-path="piecewise-sems.html"><a href="piecewise-sems.html#benefits-of-piecewise-sem"><i class="fa fa-check"></i><b>41.2.3</b> Benefits of Piecewise SEM</a></li>
<li class="chapter" data-level="41.2.4" data-path="piecewise-sems.html"><a href="piecewise-sems.html#when-to-use-each-approach"><i class="fa fa-check"></i><b>41.2.4</b> When to Use Each Approach</a></li>
<li class="chapter" data-level="41.2.5" data-path="piecewise-sems.html"><a href="piecewise-sems.html#models-differ-in-approach"><i class="fa fa-check"></i><b>41.2.5</b> Models differ in approach</a></li>
</ul></li>
<li class="chapter" data-level="41.3" data-path="piecewise-sems.html"><a href="piecewise-sems.html#sem-example-resilience-to-drought-in-arizona"><i class="fa fa-check"></i><b>41.3</b> SEM Example: Resilience to Drought in Arizona</a>
<ul>
<li class="chapter" data-level="41.3.1" data-path="piecewise-sems.html"><a href="piecewise-sems.html#chapter-12-introduction-to-piecewise-sem-in-r"><i class="fa fa-check"></i><b>41.3.1</b> Chapter 12: Introduction to Piecewise SEM in R</a></li>
</ul></li>
<li class="chapter" data-level="41.4" data-path="piecewise-sems.html"><a href="piecewise-sems.html#part-1-what-is-piecewise-sem"><i class="fa fa-check"></i><b>41.4</b> Part 1: What is Piecewise SEM?</a>
<ul>
<li class="chapter" data-level="41.4.1" data-path="piecewise-sems.html"><a href="piecewise-sems.html#chapter-13-nonlinearity-and-interaction-in-sem"><i class="fa fa-check"></i><b>41.4.1</b> Chapter 13: Nonlinearity and Interaction in SEM</a></li>
<li class="chapter" data-level="41.4.2" data-path="piecewise-sems.html"><a href="piecewise-sems.html#chapter-14-glms-with-sem-using-piecewisesem"><i class="fa fa-check"></i><b>41.4.2</b> Chapter 14: GLMs with SEM using PiecewiseSEM</a></li>
</ul></li>
<li class="chapter" data-level="41.5" data-path="piecewise-sems.html"><a href="piecewise-sems.html#overview-1"><i class="fa fa-check"></i><b>41.5</b> Overview</a>
<ul>
<li class="chapter" data-level="41.5.1" data-path="piecewise-sems.html"><a href="piecewise-sems.html#chapter-15-categorical-predictors-multigroup-sem"><i class="fa fa-check"></i><b>41.5.1</b> Chapter 15: Categorical Predictors &amp; Multigroup SEM</a></li>
<li class="chapter" data-level="41.5.2" data-path="piecewise-sems.html"><a href="piecewise-sems.html#chapter-16-multigroup-sem-in-r"><i class="fa fa-check"></i><b>41.5.2</b> Chapter 16: Multigroup SEM in R</a></li>
<li class="chapter" data-level="41.5.3" data-path="piecewise-sems.html"><a href="piecewise-sems.html#chapter-17"><i class="fa fa-check"></i><b>41.5.3</b> Chapter 17:</a></li>
</ul></li>
<li class="chapter" data-level="41.6" data-path="piecewise-sems.html"><a href="piecewise-sems.html#example-with-powerline-data"><i class="fa fa-check"></i><b>41.6</b> Example with Powerline Data</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/sarasouther/DataAnalysis" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Statistics for Ecology</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="power-analysis" class="section level1 hasAnchor" number="15">
<h1><span class="header-section-number">Chapter 15</span> Power analysis<a href="power-analysis.html#power-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="prework" class="section level2 hasAnchor" number="15.1">
<h2><span class="header-section-number">15.1</span> Prework<a href="power-analysis.html#prework" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Install packages ‘pwr’, ‘faraway’, ‘simr’, ‘simglm’, and ‘Superpower’.</p>
</div>
<div id="statistical-power" class="section level2 hasAnchor" number="15.2">
<h2><span class="header-section-number">15.2</span> Statistical power<a href="power-analysis.html#statistical-power" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>As we learned in lesson 3, Basic Statistical Test, statistical power is a measure of making a Type II error - saying that there is no treatment effect when, in fact, there is one. A power analysis is a way of estimating statistical power to either speak to the ability of your experiment to detect treatment effects or estimate sample size needed to answer the question that you are interested in with your experimental design.</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="power-analysis.html#cb77-1" tabindex="-1"></a><span class="fu">library</span>(pwr)</span>
<span id="cb77-2"><a href="power-analysis.html#cb77-2" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb77-3"><a href="power-analysis.html#cb77-3" tabindex="-1"></a><span class="fu">library</span>(simr)</span>
<span id="cb77-4"><a href="power-analysis.html#cb77-4" tabindex="-1"></a><span class="fu">library</span>(simglm)</span>
<span id="cb77-5"><a href="power-analysis.html#cb77-5" tabindex="-1"></a><span class="fu">library</span>(Superpower)</span>
<span id="cb77-6"><a href="power-analysis.html#cb77-6" tabindex="-1"></a><span class="co">#load data</span></span>
<span id="cb77-7"><a href="power-analysis.html#cb77-7" tabindex="-1"></a><span class="fu">data</span>(<span class="st">&#39;oatvar&#39;</span>, <span class="at">package=</span><span class="st">&#39;faraway&#39;</span>)</span></code></pre></div>
<p>#Using power analysis to estimate needed sample size.</p>
<p>To conduct a power analysis, you will need to know:
<em>The number of groups in your study
</em>Significance level. It is standard to use a significance level of 0.05.
<em>The power required for your experiment, which is typically set at 0.8.
</em>Effect size, which can be calculated from data from a pilot study or estimated.</p>
<p><strong>Effect size</strong> is a relativized estimate of difference between groups being compared. Generally, effect size is calculated by taking the difference between the two groups (e.g., the mean of treatment group minus the mean of the control group) and dividing it by the standard deviation of one of the groups.</p>
<p>Because effect size is converted to standard deviations units, it tells you how many standard deviations lie between the two means, and can be compared across datasets regardless of the original units of the study (which is why effect sizes are calculated for meta-analyses).</p>
<p>A classic effect size calculation is Cohen’s D calculated as <span class="math inline">\(\frac{\overline{x}_1 - \overline{x}_2}{s_{pooled}}\)</span>, where <span class="math inline">\({\overline{x}_1}\)</span> is the mean of one group, <span class="math inline">\({\overline{x}_2}\)</span> is the mean of the second group, and <span class="math inline">\(s_{pooled}\)</span> is standard deviation (typically pooled; sometimes of the control or pretest data) calculated as <span class="math inline">\(s_{pooled} = \sqrt{\frac{sd_{a}^{2}+ sd_{b}^{2}}{2}}\)</span>. Note that Cohen’s D is one of <em>many</em> ways of calculating effect size. Two other metrics are used by the ‘pwr package’: <span class="math inline">\(f\)</span>, calculated as expected standard deviation of the group means divided by the pooled within-group standard deviation, is used in our example below. Another option is eta-squared (η2). The eta-squared is the proportion of the total variance explained by the means variance.</p>
<p>It is harder to detect a smaller effect of the treatment, and easier to detect larger effects. Cohen in his 1988 book (citation below) classified effect sizes into 3 general categories for Cohen’s D (CONFIRM): a small effect is typically set at 0.1 - 0.3, a medium effect at 0.3 - 0.5, and a large effect at &gt; 0.5. <strong>Note that the range for small, medium, and large effects differ by effect size calculation</strong> Using these classifications, you can estimate the sample size for a proposed study even if you have <strong>no</strong> data.</p>
<p><strong>Cohen, J. (1988). Statistical power analysis for the behavioral sciences (2nd ed.). Hillsdale,NJ:
Lawrence Erlbaum.</strong></p>
<p>Below, we will run a power analysis with actual data, but let’s start by running a power analysis to guide experimental planning for a study when no opportunity to conduct a pilot. Imagine you are planning an experiment in which you are trialing the effect of a new fertilizer on oat growth. You plan to include three levels, a control (no fertilizer added), a moderate fertilization treatment, and a high fertilization treatment and measure height as a dependent variable.</p>
<p>In the code below, k indicates the number of groups (here: control, moderate, high), f indicates an effect size (we selected a medium effect size), sig.level indicates the significance level (0.05), and power (standard to use 0.8). To calculate the number of groups, if you have two factors, simply multiply the number of groups in each factor to get the value k. For instance, say you are looking at the effect of 2 levels of pesticide and 3 temperature levels on bee longevity, you would multiply 2 * 3, yielding 6 groups.</p>
<p><strong>Why do we use 0.8?</strong>
It is by convention, much like we set a significance level (<span class="math inline">\(\alpha\)</span>) of 0.05. At some point scientists agreed that a power level of 0.8, which means that the probability of rejecting a false null hypothesis is 0.8 (or 80%), is an acceptable risk of committing a Type II error.</p>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="power-analysis.html#cb78-1" tabindex="-1"></a><span class="fu">pwr.anova.test</span>(<span class="at">k=</span><span class="dv">3</span>, <span class="at">f=</span><span class="fl">0.3</span>, <span class="at">sig.level=</span><span class="fl">0.05</span>, <span class="at">power=</span><span class="fl">0.8</span>) </span></code></pre></div>
<pre><code>## 
##      Balanced one-way analysis of variance power calculation 
## 
##               k = 3
##               n = 36.70126
##               f = 0.3
##       sig.level = 0.05
##           power = 0.8
## 
## NOTE: n is number in each group</code></pre>
<p>In this case, we’d should include at least 37 individuals (plus a few extra) to accommodate loss of individuals during the experiment.</p>
<p>When possible, it is preferable to run a pilot experiment in order to improve experimental design. The ‘pwr’ package in R allows you to run a power analysis on various forms of data. Let’s run through several quick analyses using the ‘pwr’ package. The effect size calculations will depend on your statistical test (for a full description of tests, go to the package).</p>
<p>Since Cohen’s description of effect sizes as small, medium and large depend on each statistical test, there is an easy way to generate this information in the ‘pwr’ dataset. For example, if you are interested in determining the value associated with a small effect size for a regression, you would run the following code:</p>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="power-analysis.html#cb80-1" tabindex="-1"></a><span class="fu">cohen.ES</span>(<span class="at">test =</span> <span class="st">&#39;r&#39;</span>, <span class="at">size =</span> <span class="st">&#39;small&#39;</span>)</span></code></pre></div>
<pre><code>## 
##      Conventional effect size from Cohen (1982) 
## 
##            test = r
##            size = small
##     effect.size = 0.1</code></pre>
<p>Note that you have several test options here:
<em>r = regression
</em>r; alternative = ‘two.sided’ = correlation (can specify direction ‘greater’) - not 100 percent sure I’m right here…
<em>p =
</em>t = for t-test (type = ‘paired’; you can select between two population to a repeated measure test)
<em>anov = anova
</em>chisq = chi sq tests
*f2 = glms</p>
<p>The ‘pwr’ package is nice for quick looks at power for simple analyses with no previous data. Note: that you can calculate effect sizes from data by hand and plug them into ‘pwr’ to generate sample sizes or power assessments.</p>
<p>Let’s check this out with the ‘oatvar dataset’.</p>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="power-analysis.html#cb82-1" tabindex="-1"></a><span class="fu">ggplot</span>(oatvar, <span class="fu">aes</span>(<span class="at">y=</span>yield, <span class="at">x=</span>block, <span class="at">color=</span>variety)) <span class="sc">+</span> </span>
<span id="cb82-2"><a href="power-analysis.html#cb82-2" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb82-3"><a href="power-analysis.html#cb82-3" tabindex="-1"></a>    <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x=</span><span class="fu">as.integer</span>(block)))</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-59-1.png" width="960" style="display: block; margin: auto;" /></p>
<p>The cbpp is a dataset on contagious bovine pleuropneumonia. Data description is here:
<a href="https://rdrr.io/cran/lme4/man/cbpp.html" class="uri">https://rdrr.io/cran/lme4/man/cbpp.html</a></p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="power-analysis.html#cb83-1" tabindex="-1"></a><span class="fu">library</span>(simr)</span>
<span id="cb83-2"><a href="power-analysis.html#cb83-2" tabindex="-1"></a><span class="fu">head</span>(cbpp)</span></code></pre></div>
<pre><code>##   herd incidence size period obs
## 1    1         2   14      1   1
## 2    1         3   12      2   2
## 3    1         4    9      3   3
## 4    1         0    5      4   4
## 5    2         3   22      1   5
## 6    2         1   18      2   6</code></pre>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="power-analysis.html#cb85-1" tabindex="-1"></a>cbpp<span class="sc">$</span>obs <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(cbpp)</span></code></pre></div>

</div>
<div id="describing-data" class="section level2 hasAnchor" number="15.3">
<h2><span class="header-section-number">15.3</span> Describing data<a href="power-analysis.html#describing-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>First, let’s take a spin with data description. We are starting here to introduce a few concepts that will be important to understand, as we launch into statistical analysis. We will start by describing continuous data.</p>
<p>Let’s use a simplified version of a dataset that I’m working with right now to look at the performance of several species of pollinator-friendly native species in agricultural gardens. Eventually, we’d like to develop seed to provide to restorationists for restoration of arid and semiarid grasslands. To do this, we need to understand how reliable these species are at establishing, producing seed, and attracting pollinators. Initially, we are conducting experiments with multiple populations of each species to determine how consistently plants grow, reproduce, and perform. Here, We will take a look at the initial heights of 1 population of one species, <em>Asclepias subverticulata</em>.</p>
<p>When doing an actual research write-up, I ask myself ‘What is the most important information for my audience to know about this dataset?’ to guide what descriptions of the data to include. Here, we are just going to play around with numbers and R code!</p>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="power-analysis.html#cb86-1" tabindex="-1"></a><span class="co">#create vector of heights (cm) of one population of A. subverticulata</span></span>
<span id="cb86-2"><a href="power-analysis.html#cb86-2" tabindex="-1"></a>sedonapopulation <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">7</span>, <span class="dv">8</span>, <span class="dv">9</span>)</span>
<span id="cb86-3"><a href="power-analysis.html#cb86-3" tabindex="-1"></a><span class="co">#take the mean</span></span>
<span id="cb86-4"><a href="power-analysis.html#cb86-4" tabindex="-1"></a><span class="fu">mean</span>(sedonapopulation)</span></code></pre></div>
<pre><code>## [1] 5.142857</code></pre>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="power-analysis.html#cb88-1" tabindex="-1"></a><span class="co">#calculate variance</span></span>
<span id="cb88-2"><a href="power-analysis.html#cb88-2" tabindex="-1"></a><span class="fu">var</span>(sedonapopulation)</span></code></pre></div>
<pre><code>## [1] 7.47619</code></pre>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="power-analysis.html#cb90-1" tabindex="-1"></a><span class="co">#calculate standard deviation</span></span>
<span id="cb90-2"><a href="power-analysis.html#cb90-2" tabindex="-1"></a><span class="fu">sd</span>(sedonapopulation)</span></code></pre></div>
<pre><code>## [1] 2.734262</code></pre>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="power-analysis.html#cb92-1" tabindex="-1"></a><span class="co">#calculate standard error</span></span>
<span id="cb92-2"><a href="power-analysis.html#cb92-2" tabindex="-1"></a><span class="co">#base r doesn&#39;t have this function</span></span>
<span id="cb92-3"><a href="power-analysis.html#cb92-3" tabindex="-1"></a><span class="co">#so we have to write our own</span></span>
<span id="cb92-4"><a href="power-analysis.html#cb92-4" tabindex="-1"></a>std_error <span class="ot">&lt;-</span> <span class="cf">function</span>(x) <span class="fu">sd</span>(x)<span class="sc">/</span><span class="fu">sqrt</span>(<span class="fu">length</span>(x))</span>
<span id="cb92-5"><a href="power-analysis.html#cb92-5" tabindex="-1"></a><span class="fu">std_error</span>(sedonapopulation)</span></code></pre></div>
<pre><code>## [1] 1.033454</code></pre>
<p>Most of the time when writing up results, you present a mean (sum of numbers divided by the number of observations), and an estimate of variation (a measure of how different the observations are). Here, we calculated three estimates variation, variance, standard deviation, and standard error.</p>
<p>Since you will occasionally need to include equations in your write-ups, let’s get use to mathematical syntax, with these simple examples.</p>
<p>The formula for the sample mean is: <span class="math inline">\(\mu = \frac{\Sigma x_i}{n}\)</span>;
where <span class="math inline">\(\mu\)</span> indicates the sample mean (sample = group of numbers we are looking at);
<span class="math inline">\(\Sigma\)</span> means to add what ever follows;
<span class="math inline">\(x_{i}\)</span> is the value of one observation; (subscript i is often used to indicate that the action should be repeated for all values);
<span class="math inline">\(n\)</span> is the number of observations</p>
<p><em>Why didn’t we just use <span class="math inline">\(\bar{x}\)</span> to indicate the mean?</em>
Because statisticians typically use <span class="math inline">\(\bar{x}\)</span> to indicate the true mean of the population, and <span class="math inline">\(\mu\)</span> to indicate the sample mean!</p>
<p>Just to show you, what the mean() function is doing, let’s run:</p>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="power-analysis.html#cb94-1" tabindex="-1"></a>sum <span class="ot">=</span> <span class="dv">3</span><span class="sc">+</span><span class="dv">3</span><span class="sc">+</span><span class="dv">3</span><span class="sc">+</span><span class="dv">3</span><span class="sc">+</span><span class="dv">7</span><span class="sc">+</span><span class="dv">8</span><span class="sc">+</span><span class="dv">9</span> <span class="co">#add all the numbers in the sample</span></span>
<span id="cb94-2"><a href="power-analysis.html#cb94-2" tabindex="-1"></a>n <span class="ot">=</span> <span class="fu">length</span>(sedonapopulation) <span class="co">#or you can just calculate the number of height measurements</span></span>
<span id="cb94-3"><a href="power-analysis.html#cb94-3" tabindex="-1"></a>mean <span class="ot">=</span> sum<span class="sc">/</span>n; mean <span class="co">#divide sum by number</span></span></code></pre></div>
<pre><code>## [1] 5.142857</code></pre>
<p>This formula is simple, but sometimes with more complex formulas, I will solve the equations by hand, to make sure that I understand what is happening!</p>
<p>The formula for variance is: <span class="math inline">\(S^{2} = \frac{\Sigma(x_i - \mu)^{2}}{n - 1}\)</span>
where <span class="math inline">\(S^{2}\)</span> is the sample variance;
<span class="math inline">\(\mu\)</span> is the sample mean (remember from above);
<span class="math inline">\(x_{i}\)</span> is the value of one observation;
<span class="math inline">\(n\)</span> is the number of observations</p>
<p>In other words:</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="power-analysis.html#cb96-1" tabindex="-1"></a><span class="co">#We determine how much each observation varies from the mean.</span></span>
<span id="cb96-2"><a href="power-analysis.html#cb96-2" tabindex="-1"></a>diffobs1 <span class="ot">=</span> mean <span class="sc">-</span> <span class="dv">3</span></span>
<span id="cb96-3"><a href="power-analysis.html#cb96-3" tabindex="-1"></a>diffobs2 <span class="ot">=</span> mean <span class="sc">-</span> <span class="dv">3</span></span>
<span id="cb96-4"><a href="power-analysis.html#cb96-4" tabindex="-1"></a>diffobs3 <span class="ot">=</span> mean <span class="sc">-</span> <span class="dv">3</span></span>
<span id="cb96-5"><a href="power-analysis.html#cb96-5" tabindex="-1"></a>diffobs4 <span class="ot">=</span> mean <span class="sc">-</span> <span class="dv">3</span></span>
<span id="cb96-6"><a href="power-analysis.html#cb96-6" tabindex="-1"></a>diffobs5 <span class="ot">=</span> mean <span class="sc">-</span> <span class="dv">7</span> </span>
<span id="cb96-7"><a href="power-analysis.html#cb96-7" tabindex="-1"></a>diffobs6 <span class="ot">=</span> mean <span class="sc">-</span> <span class="dv">8</span></span>
<span id="cb96-8"><a href="power-analysis.html#cb96-8" tabindex="-1"></a>diffobs7 <span class="ot">=</span> mean <span class="sc">-</span> <span class="dv">9</span> </span>
<span id="cb96-9"><a href="power-analysis.html#cb96-9" tabindex="-1"></a></span>
<span id="cb96-10"><a href="power-analysis.html#cb96-10" tabindex="-1"></a><span class="co">#Then we square each of these. </span></span>
<span id="cb96-11"><a href="power-analysis.html#cb96-11" tabindex="-1"></a>diffobj1_sq <span class="ot">=</span> diffobs1<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb96-12"><a href="power-analysis.html#cb96-12" tabindex="-1"></a>diffobj2_sq <span class="ot">=</span> diffobs2<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb96-13"><a href="power-analysis.html#cb96-13" tabindex="-1"></a>diffobj3_sq <span class="ot">=</span> diffobs3<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb96-14"><a href="power-analysis.html#cb96-14" tabindex="-1"></a>diffobj4_sq <span class="ot">=</span> diffobs4<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb96-15"><a href="power-analysis.html#cb96-15" tabindex="-1"></a>diffobj5_sq <span class="ot">=</span> diffobs5<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb96-16"><a href="power-analysis.html#cb96-16" tabindex="-1"></a>diffobj6_sq <span class="ot">=</span> diffobs6<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb96-17"><a href="power-analysis.html#cb96-17" tabindex="-1"></a>diffobj7_sq <span class="ot">=</span> diffobs7<span class="sc">^</span><span class="dv">2</span></span></code></pre></div>
<p><em>Why do we square the differences rather than just adding them up?</em>
Because differences will be positive and negative. If we added them without squaring, sample differences would negate each other. We want an estimate of the absolute differences of samples from the mean.</p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="power-analysis.html#cb97-1" tabindex="-1"></a><span class="co">#Then we add the differences up.</span></span>
<span id="cb97-2"><a href="power-analysis.html#cb97-2" tabindex="-1"></a>sumofsquares <span class="ot">=</span> <span class="fu">sum</span>(diffobj1_sq, diffobj2_sq, diffobj3_sq, diffobj4_sq, diffobj5_sq, diffobj6_sq, diffobj7_sq)</span>
<span id="cb97-3"><a href="power-analysis.html#cb97-3" tabindex="-1"></a><span class="co">#Divide the sum of squares by n - 1.</span></span>
<span id="cb97-4"><a href="power-analysis.html#cb97-4" tabindex="-1"></a>variance <span class="ot">=</span> sumofsquares<span class="sc">/</span>(n<span class="dv">-1</span>); variance </span></code></pre></div>
<pre><code>## [1] 7.47619</code></pre>
<p><em>Why n - 1 instead of n?</em></p>
<p>One reason is that, theoretically, because we are taking the mean of a sample, rather than all individuals, we underestimate the variance, so taking n-1 corrects that bias. Consider it a penalty for measuring a sample, not the entire population! Another practical reason is that dividing by n-1 makes the variance of a single sample undefined (unsolvable) rather than zero (solvable)</p>
<p>For standard deviation, we just take the square root of the variance, to remove the effect of squaring the differences when calculating the variance, and thus contextualizing our estimate of variation with regard to the mean. For example, the variance for the Sedona population is 7.48, larger than the sample mean of 5.12; while the standard deviation is 2.73, indicating that you would expect most observations to be 5.12 +/- 2.73 (we’ll get to quantiles in a minute).</p>
<p>The formula for standard deviation is: <span class="math inline">\(\sigma = \sqrt\frac{\Sigma(x_i - \mu)^{2}}{n - 1}\)</span>
where <span class="math inline">\(\sigma\)</span> is the sample variance;
<span class="math inline">\(\mu\)</span> is the sample mean;
<span class="math inline">\(x_{i}\)</span> is the value of one observation;
<span class="math inline">\(n\)</span> is the number of observations.</p>
<p>Finally, standard error and confidence intervals (we’ll get to confidence intervals later) are the most common metrics of variance presented in journals.</p>
<p>The formula for standard error is: <span class="math inline">\(SE = \frac{\sigma}{\sqrt n}\)</span>
where <span class="math inline">\(SE\)</span> is standard error of the sample;
<span class="math inline">\(\sigma\)</span> is the standard deviation; and
<span class="math inline">\(n\)</span> is the number of samples.</p>
<p><em>Why do we divide the standard deviation by the square root of the sample size to get standard error?</em></p>
<p>While standard deviation measures the variation of the sample, standard error is meant to estimate the variation of the entire population of samples, if we could measure all individuals accurately. By dividing by the <span class="math inline">\(\sqrt n\)</span>, the larger the sample size, the lower the error, because you have a more complete estimate of the true mean. In other words, standard deviation is just a measure of the variation of our sample, while standard error also incorporates information about our sampling process (how many individuals we have sampled). <em>Want to delve deep into standard error and deviation (me neither - ha)?: Google central limit theorem + standard error / standard deviation.</em></p>
<p>Means and variance measures are the most common way to describe quantitative data. However, several other metrics are useful for understanding the nature of your data and making decisions about analyses. A comprehensive understanding of your dataset includes describing these four features:</p>
<p><em>Location (Mean, Median)
</em>Spread (Variability)
<em>Shape (Normal, skewed)
</em>Outliers</p>
<p>We’ve talked about means. The median is just the central number in the dataset, and helps you identify skewness.</p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="power-analysis.html#cb99-1" tabindex="-1"></a><span class="co">#an example of an unskewed population</span></span>
<span id="cb99-2"><a href="power-analysis.html#cb99-2" tabindex="-1"></a>sedona_unskewed <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>, <span class="dv">7</span>)</span>
<span id="cb99-3"><a href="power-analysis.html#cb99-3" tabindex="-1"></a><span class="fu">mean</span>(sedona_unskewed)</span></code></pre></div>
<pre><code>## [1] 4</code></pre>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="power-analysis.html#cb101-1" tabindex="-1"></a><span class="fu">median</span>(sedona_unskewed)</span></code></pre></div>
<pre><code>## [1] 4</code></pre>
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb103-1"><a href="power-analysis.html#cb103-1" tabindex="-1"></a><span class="co">#previous sedona population; skewed</span></span>
<span id="cb103-2"><a href="power-analysis.html#cb103-2" tabindex="-1"></a>sedonapopulation <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">7</span>, <span class="dv">8</span>, <span class="dv">9</span>)</span>
<span id="cb103-3"><a href="power-analysis.html#cb103-3" tabindex="-1"></a><span class="fu">mean</span>(sedonapopulation)</span></code></pre></div>
<pre><code>## [1] 5.142857</code></pre>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="power-analysis.html#cb105-1" tabindex="-1"></a><span class="fu">median</span>(sedonapopulation)</span></code></pre></div>
<pre><code>## [1] 3</code></pre>
<p>In an unskewed population, the mean will equal the median. Skew may not seem important, but it has statistical ramifications, AND it tells us something meaningful about the data. For instance, what if I said that mean price of a home in Flagstaff is 350K, but the median price of a home is 300K? We would know the that average house prices are driven up by a smaller number of expensive homes.</p>
<p>We can quantify skew by comparing means and medians (mean &gt; median = right-skewed; median &gt; mean = left-skewed), but it is helpful to visualize the shape of data with a <strong>histogram</strong>. A <strong>histogram</strong> is a graph of the frequency of different measurements.</p>
<p>Let’s add a few more observations to our Sedona populations (skewed and unskewed) and check out the look of the data!</p>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="power-analysis.html#cb107-1" tabindex="-1"></a>sedona_unskewed <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">7</span>, <span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">6</span>, <span class="dv">6</span>, <span class="dv">5</span>, <span class="dv">5</span>, <span class="dv">5</span>, <span class="dv">5</span>, <span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">4</span>, <span class="fl">0.5</span>)</span>
<span id="cb107-2"><a href="power-analysis.html#cb107-2" tabindex="-1"></a><span class="fu">mean</span>(sedona_unskewed)</span></code></pre></div>
<pre><code>## [1] 3.975</code></pre>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="power-analysis.html#cb109-1" tabindex="-1"></a><span class="fu">median</span>(sedona_unskewed)</span></code></pre></div>
<pre><code>## [1] 4</code></pre>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb111-1"><a href="power-analysis.html#cb111-1" tabindex="-1"></a><span class="co">#I&#39;m renaming sedonapopulation, sedona_skewed for this example</span></span>
<span id="cb111-2"><a href="power-analysis.html#cb111-2" tabindex="-1"></a>sedona_skewed <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">7</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">6</span>, <span class="dv">7</span>, <span class="dv">8</span>, <span class="dv">9</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">2</span>)</span>
<span id="cb111-3"><a href="power-analysis.html#cb111-3" tabindex="-1"></a><span class="fu">mean</span>(sedona_skewed)</span></code></pre></div>
<pre><code>## [1] 4.454545</code></pre>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="power-analysis.html#cb113-1" tabindex="-1"></a><span class="fu">median</span>(sedona_skewed)</span></code></pre></div>
<pre><code>## [1] 4</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-67-1.png" width="960" style="display: block; margin: auto;" />
In this relatively unskewed example, the tails are approximately even. This shape is also referred to as a normal or Gaussian distribution.
<img src="_main_files/figure-html/unnamed-chunk-68-1.png" width="960" style="display: block; margin: auto;" />
Here, we superimposed the bellshaped Normal or Gaussian distribution.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-69-1.png" width="960" style="display: block; margin: auto;" />
In this example of skewed data, the tail tapers to the right, indicated that the data is skewed to the right.</p>
<p>In order to explain outliers, we need to look at quantiles! Quantiles are proportions of your data, in other words a way to break your data into chunks to understand spread. You can break your data into as many quantiles as you would like, but it is most common to break your data into 4 parts, also called quartiles. (If you break data into 5 parts, the components are called quintiles, 10 parts = deciles, 100 parts = percentiles).</p>
<p>When you break data into quartiles, roughly 25 percent of the data occurs within each data chunk. The first chunk of the dataset contains 25% of the data (25th percentile; 25% of the data fall at or below this cut-off) is called the first quartile, the 50th percentile is called the sample median or the second quartile, the 75th percentile is called the third quartile.</p>
<p>Box and whisker plots are commonly used to quickly examine quartiles. Let’s check out our plant height data again, using a box and whisker plot.
<img src="_main_files/figure-html/unnamed-chunk-70-1.png" width="960" style="display: block; margin: auto;" />
In the plot shown here, the box encapsulates the Interquartile Range (IQR); the center of the data ranging from the 25th percentile to the 75th. The black line in the middle of the box is the median (also called the 50th percentile, because it bisects the dataset; half of the data occur above the median and half below). The lines emerging from the box (whiskers) indicate the extent of the first and third quartiles, and usually corresponding with the minimum and maximum values of the dataset, unless there are <strong>outliers</strong>. An outlier is a datapoint that occurs outside of the 1st or 3rd quantile. Let’s add one to our Sedona dataset, and see how it is represented on the box and whisker plot.</p>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="power-analysis.html#cb115-1" tabindex="-1"></a><span class="co">#Let&#39;s add a plant height of 20.</span></span>
<span id="cb115-2"><a href="power-analysis.html#cb115-2" tabindex="-1"></a>sedona_skewed <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">7</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">6</span>, <span class="dv">7</span>, <span class="dv">8</span>, <span class="dv">9</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">2</span>, <span class="dv">20</span>)</span>
<span id="cb115-3"><a href="power-analysis.html#cb115-3" tabindex="-1"></a><span class="fu">boxplot</span>(sedona_skewed, <span class="at">main=</span><span class="st">&quot;Skewed&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;Plant height (cm)&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-71-1.png" width="960" style="display: block; margin: auto;" />
The outlier appears as a dot on the box and whisker plot, and is the maximum value of the dataset.</p>
<p>One other thing to note: Standard deviation also breaks data into meaningful segments, but is only used when data conform to a normal distribution; the mean +/- 1 SD accounts for 68% of the data, +/-2 SDs contains 95% of data, and +/- 3SD includes 99% of data. That said, I’ve never presented standard deviation in a manuscript; it is much more common to include standard error or confidence intervals (discussed later).</p>
<p>We’ve played around a lot with data, but what do you actually need to take away from this?:</p>
<p><em>Data types (Categorical, Numerical discrete, Numerical continuous, Ordinal)
<strong>Why?</strong> We will select analyses based on data type.
</em>The two basic questions that most statistical analyses answer.
<strong>Why?</strong> This will help you define what statistics can and can’t do and bound our learning space!
<em>Ways to describe numerical continuous data (Location, Spread, Shape, Outliers).
<strong>Why?</strong> You will describe your results using these concepts in write-up AND these concepts will be important for certain analyses.
</em>Know how to calculate mean, median, and standard error.
<strong>Why?</strong> These are typical ways to describe data in results sections.
<em>Start to familiarize yourself with mathematical annotation.
<strong>Why?</strong> You may need to include equations in your methods section.
</em>Start to familiarize yourself with R code.
<strong>Why?</strong> Most researchers now use R to analyze, describe, and visualize their data.
*Be able to interpret a histogram and box-whisker plot.
<strong>Why?</strong> These are commonly used ways to visualize data.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="ecological-sampling.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="selecting-statistical-tests.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/sarasouther/DataAnalysis/edit/main/07-PowerAnalysis.Rmd",
    "text": "Edit this page"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["_main.epub"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
